### ISSUE TITLE
Add TLS support for istio service in Helm deployments

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#1]

**Comment by tzuryby** [comment]
@xavier-rbz what is the status of this one?

**Comment by xavier-rbz** [comment]
Still open

**Comment by tzuryby** [comment]
@xavier-rbz this is done, right?

**Comment by xavier-rbz** [comment]
I've looked into it a little more... Following the istio documentation (https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/) is all that is required, we don't have to implement anything as it's a standard istio feature.
I'll close this.
