### ISSUE TITLE
`deny bot` is overriding `deny` when human is verified

### ISSUE THREAD

**Issue by tzuryby** [curiefense/curiefense#111]
**Deny bot is overriding deny when human is verified**
if a session matched with deny and deny bot, and the session is post challenge with success, it will not fall into deny as intended.

**To Reproduce**
1. Go to ACL
2. Set deny bot 'all'
3. Set deny 'all'
4. Publish and create an HTTP request from a browser
5. See that you reach the service.

**Expected behavior**
Challenged, then blocked. not passed.

**Comment by flaper87** [comment]
@tzuryby thanks for the steps to reproduce. I've removed you from the assignees' list, for now, hoping that someone else can take this on and help us verify it.

**Comment by flaper87** [comment]
@tzuryby @Aviv-Galmidi is this a problem in the UI? Or is the curiefense protection doing this?

**Comment by bartavelle** [comment]
This was a filtering problem, that should be fixed now.
