### ISSUE TITLE
Automate envoy build

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#121]
Current state: envoy binaries are built manually, and then committed to this repository.

Change to be done: build the envoy binary using CI from [our envoy repository](https://github.com/curiefense/envoy), push this image, and copy the binary from that image.

**Comment by flaper87** [comment]
Love the goal of this issue! I guess we can tackle it once #221 is done :crossed_fingers:

**Comment by xavier-rbz** [comment]
I'd rather do this first, and then #221: envoy is an istio component, therefore producing envoy binaries that are usable with our code is a prerequisite.

**Comment by flaper87** [comment]
> Change to be done: build the envoy binary using CI from [our envoy repository](https://github.com/curiefense/envoy), push this image, and copy the binary from that image.

Perhaps we could start by adding a GH action to the envoy-cf repo and making sure images are pushed from there rather than the build/push as part of the curiefense repo?

**Comment by xavier-rbz** [comment]
Now, envoy is being built from two repositories:
* https://github.com/curiefense/envoy to build the envoy binary that is used for curieproxy-envoy images ([Dockerfile](https://github.com/curiefense/curiefense/blob/main/curiefense/images/curieproxy-envoy/Dockerfile)
* https://github.com/curiefense/istio-proxy for the envoy binary that is used for curieproxy-istio images ([Dockerfile](https://github.com/curiefense/curiefense/blob/main/curiefense/images/curieproxy-istio/Dockerfile))

=> The binaries that are built from these repos are stored as Docker images, and referenced in this repo.
The build process uses GitHub actions. It runs on a "self hosted" runner, since the build takes a longer time than what github allows (6 hours with 2 cores).
Closing.
