### ISSUE TITLE
Add Snyk

### ISSUE THREAD

**Issue by jdorfman** [curiefense/curiefense#133]
via @caniszczyk #132 

> You have CodeSQL security scanning going which helps fulfill this requirement imho: https://github.com/curiefense/curiefense/security/code-scanning

**IMHO I would add Snyk potentially here too to help, along with Code Climate
etc :)**

**Comment by flaper87** [comment]
> via @caniszczyk #132
> 
> > You have CodeSQL security scanning going which helps fulfill this requirement imho: https://github.com/curiefense/curiefense/security/code-scanning
> 
> **IMHO I would add Snyk potentially here too to help, along with Code Climate etc :)**

I would add it because I'm interested in scanning the container images too

**Comment by jdorfman** [comment]
> I would add it because I'm interested in scanning the container images too

@tzuryby added it :)

![image](https://user-images.githubusercontent.com/398230/108603333-406cf500-735c-11eb-98f9-768d326d8c72.png)

![image](https://user-images.githubusercontent.com/398230/108603342-44007c00-735c-11eb-9044-e88e6ad64c03.png)
