### ISSUE TITLE
Bootstrap data has two buckets named "prod"

### ISSUE THREAD

**Issue by Aviv-Galmidi** [curiefense/curiefense#15]
Bootstrap data -> database master -> key publishinfo -> buckets
There are two buckets called prod. This is not a valid state and causes issues in Publish Configuration page

![Screen Shot 2020-11-09 at 18 10 18](https://user-images.githubusercontent.com/10487148/98565957-e49fc400-22b6-11eb-8d84-57d0407152d2.png)

**Comment by Lastpixl** [comment]
Hi Aviv,

It seems to have been fixed since then. The "bootstrap" configuration [here](https://github.com/curiefense/curiefense/blob/master/curiefense/images/confserver/bootstrap/db.conf.json) now has two different names. I tested it with docker-compose, names were different as expected.
Closing.

**Comment by xavier-rbz** [comment]
Hi Aviv,

It seems to have been fixed since then. The "bootstrap" configuration here now has two different names. I tested it with docker-compose, names were different as expected.
Closing.
