### ISSUE TITLE
UI - WAF Policy should autocomplete and suggest possible matches for WAF Rules input

### ISSUE THREAD

**Issue by Aviv-Galmidi** [curiefense/curiefense#170]
Policies & Rules -> WAF Policies

The user is able to add rule entries at the bottom of the page to either Headers, Cookies, or Args
The user is able to add WAF rules IDs to be excluded from the new rule entry

Currently the user needs to type the IDs themselves, we can use our autocomplete component and add possible suggestions and autocomplete to the process from our list of WAF Rules

**Comment by jdorfman** [comment]
@Aviv-Galmidi what milestone is this for?

**Comment by Aviv-Galmidi** [comment]
It's not needed for 1.3.0. I'd assume whatever milestone comes after that, but we don't have anything in that fashion at the moment

Simply added the task for the future backlog as a "will do in the feature" task of sort as it's not urgent just a good feature to add when we have the time

**Comment by jdorfman** [comment]
Gotcha, just want to make sure I keep the Release Notes up to date. =)
