### ISSUE TITLE
Missing retry logic in curielogger's ES initialization code paths

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#173]
Hi,

Testing a deployment of #168 in Helm, I encountered an error I had not obtained when testing #117: curielogger failed at `client.ILM.GetLifecycle` because ES wasn't ready yet. https://github.com/curiefense/curiefense/blob/63b64f271f313f75f1c787bd49ac444e4671f735/curiefense/curielogger/curielogger/outputs.elasticsearch.go#L383

I think adding some retry logic here could help, maybe something similar to what @flaper87 did in #168's in `ConfigureKibana`.

**Comment by xavier-rbz** [comment]
Same problem when running this in Helm:
```
2021/02/25 21:35:33 [ERROR] There was an error while querying the ILM Policies dial tcp 172.18.0.5:9200: connect: connection refused
```

**Comment by flaper87** [comment]
Glad you are bringing this up.

* Did the helm deployment fail? 
* Should we fail the deployment?

In the implementation, I thought of not retrying and also not failing the deployment in the case ES was not up. However, I can see that we may want to have a retry and then properly deactivate the logger if the initialization process failed. This sounds like an ideal scenario, considering that curielogger supports more than one logger at a time

**Comment by flaper87** [comment]
Alright, I think I found a better solution that will, eventually (once we move all the outputs to follow the new Configuration steps/structure), work for every output. For now it covers Logstash and Elasticsearch. Fluentd will come next

**Comment by xavier-rbz** [comment]
> we may want to have a retry and then properly deactivate the logger if the initialization process failed

Sounds good, provided we retry longer than the typical ES/Kibana initialization time.
