### ISSUE TITLE
Create cname for podcast

### ISSUE THREAD

**Issue by jdorfman** [curiefense/curiefense#184]
Log in to your DNS provider and create the following record:

`CNAME	podcast.curiefense.io	→	hosted.fireside.fm`

**Comment by flaper87** [comment]
@jdorfman Do we have a repo/place for media-related tasks/issues? If not, I think we could/should create one. I would rather keep issues in the curiefense repo for things directly related to the software, architecture, etc.

**Comment by jdorfman** [comment]
@flaper87 good call, I created a media repo so I will drop it there. Feel free to delete this issue

**Comment by tzuryby** [comment]
on it

**Comment by tzuryby** [comment]
done.

https://dnschecker.org/#CNAME/podcast.curiefense.io

**Comment by tzuryby** [comment]
if you need help with certificate issuancelet me know.

**Comment by jdorfman** [comment]
Thanks @tzuryby =)
