### ISSUE TITLE
Logs not sent to logstash

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#190]
Deployed from `main` (1b962bfbbb0ffe0a45a601a31bba2fd61922d50a) using helm.

Configuration looks OK, I have these variables in the curielogger container:
```
root@curielogger-6665fcd7dc-l6sfm:/# export|grep CUR
declare -x CURIELOGGER_INITIALIZE_KIBANA_INDEX="true"
declare -x CURIELOGGER_KIBANA_URL="http://kibana:5601/"
declare -x CURIELOGGER_METRICS_PROMETHEUS_ENABLED="true"
declare -x CURIELOGGER_OUTPUTS_LOGSTASH_ENABLED="true"
declare -x CURIELOGGER_OUTPUTS_LOGSTASH_URL="http://logstash:5001/"
(...)
```

Yet in the output, I cannot see debug messages related to logstash:
```
kubectl logs -n curiefense curielogger-6665fcd7dc-67l88
2021/02/28 11:48:10 Starting curielogger v0.3-dev1
2021/02/28 11:48:10 [INFO] Log level set at debug
2021/02/28 11:48:10 [INFO] Channel capacity set at 65536
2021/02/28 11:48:10 Prometheus exporter listening on :2112
2021/02/28 11:48:10 GRPC server listening on :9001
2021/02/28 11:48:10 [INFO] Prometheus (prometheus) metrics updating routine started
```

No kibana or elasticsearch initialization takes place. Since we're in debug mode, I expected to see logs from https://github.com/curiefense/curiefense/blob/main/curiefense/curielogger/curielogger/main.go#L487 https://github.com/curiefense/curiefense/blob/main/curiefense/curielogger/curielogger/main.go#L826 https://github.com/curiefense/curiefense/blob/main/curiefense/curielogger/curielogger/main.go#L834

**Comment by xavier-rbz** [comment]
After adding debug code (https://github.com/xavier-rbz/curiefense/commit/c56ed5d8418e20cec08dd766b42b9ac2656c6e2d), I can see that changes to `CURIELOGGER_LOG_LEVEL` are reflected in the output, but not changes to `CURIELOGGER_OUTPUTS_LOGSTASH_ENABLED` or `CURIELOGGER_OUTPUTS_LOGSTASH_URL`.

Sample output after setting `CURIELOGGER_OUTPUTS_LOGSTASH_ENABLED=true` in `docker-compose.yml`:
```
curielogger      | 2021/02/28 18:31:24 [INFO] Log level set at debug
curielogger      | channel_capacity: 65536
curielogger      | log_level: debug
curielogger      | outputs:
curielogger      | - elasticsearch:
curielogger      |     enabled: false
curielogger      |     initialize: true
curielogger      |     kibana_url: http://kibana:5601
curielogger      |     overwrite: true
curielogger      |     url: http://elasticsearch:9200/
curielogger      |     use_data_stream: true
curielogger      | - logstash:
curielogger      |     elasticsearch:
curielogger      |       enabled: false
curielogger      |       initialize: true
curielogger      |       kibana_url: http://kibana:5601
curielogger      |       overwrite: true
curielogger      |       url: http://elasticsearch:9200/
curielogger      |       use_data_stream: true
curielogger      |     enabled: false
curielogger      |     url: http://logstash:5001/
```

**Comment by flaper87** [comment]
> Sample output after setting CURIELOGGER_OUTPUTS_LOGSTASH_ENABLED=true in docker-compose.yml

mmh, interesting! Sounds like the environment variable is not being read properly. Will take a look

**Comment by xavier-rbz** [comment]
Reopening: the problem is still present, in another form.
Now setting `CURIELOGGER_OUTPUTS_LOGSTASH_ENABLED=true` does change the value... But viper13 unmarshals it as a string (`"true"`) instead of a boolean (`true`).
This is seems to be this issue: https://github.com/spf13/viper/issues/937
Since marshalling environment to booleans doesn't seem to be supported yet, should we convert booleans to strings? That's less elegant... but it will work.

**Comment by flaper87** [comment]
> Since marshalling environment to booleans doesn't seem to be supported yet, should we convert booleans to strings? That's less elegant... but it will work.


I think we'll have to use something different than `viper` for environment variables configs, which requires more changes. I was planning to do this later but I think we will have to prioritize it.

**Comment by xavier-rbz** [comment]
It works now, closing.
