### ISSUE TITLE
Use a modern version of Istio

### ISSUE THREAD

**Issue by howardjohn** [curiefense/curiefense#221]
The version of Istio bundled is out of support: https://istio.io/latest/news/support/announcing-1.5-eol/ and already has (a few) known unlatched vulnerabilities.

It would be great to use a version that is currently in support.

I am an Istio maintainer so feel free to ask any questions if you need help.

**Comment by jdorfman** [comment]
Hey @howardjohn! Thanks for bringing this to our attention. I will get this prioritized. =)

**Comment by jdorfman** [comment]
@xavier-rbz any updates on this for @howardjohn?

**Comment by xavier-rbz** [comment]
Sure, I plan to finish #232 (fix failing e2e tests) first: that will allow us to catch regressions.
Then, #121 (automate envoy build).

And at that point we'll be ready to update istio.
Cheers

**Comment by jdorfman** [comment]
Great thanks @xavier-rbz

**Comment by flaper87** [comment]
I've removed @phil777 and myself from the assignees list. Let's always have a single assignee per issue so that we can communicate better who's working on what :smile:

**Comment by xavier-rbz** [comment]
The main branch now deploys istio 1.9.3. Documentation needs to be updated, so I'll keep this issue open for now.

**Comment by flaper87** [comment]
> The main branch now deploys istio 1.9.3. Documentation needs to be updated, so I'll keep this issue open for now.

Added a `needs/docs` label

**Comment by joadr** [comment]
All Istio versions prior to 1.10 have known security issues now:

https://istio.io/latest/docs/releases/supported-releases/#supported-releases-without-known-common-vulnerabilities-and-exposures-cves

**Comment by xavier-rbz** [comment]
Work is ongoing to support istio 1.13.2! See [here](https://github.com/curiefense/curiefense-helm/tree/cf-1.13.2) and [here](https://github.com/curiefense/curiefense/tree/cf-1.13.2).

**Comment by xavier-rbz** [comment]
Support for istio 1.13.2 has been merged in main.
