### ISSUE TITLE
Mask PII data

### ISSUE THREAD

**Issue by tzuryby** [curiefense/curiefense#245]
**Masking PII data should be used with salted hash provided as secret**
Can be random one if not provided.
masking method should be either:
 1. hinted. e.g. `+134****23`
 2. hinted+hash. e.g. `myname@HASH`
3. complete hash

**Comment by flaper87** [comment]
@tzuryby this sounds relevant. Do you know what the current impact of this bug is? has this been worked on to any extent?

**Comment by bartavelle** [comment]
Questions:

 * where is it configured right now? Is that the meaning of the "mask" field I saw on the WAF side? What is the semantic of this field?
 * what should be done with regards to URL arguments, as they are in multiple fields, such as the full URI, in url-encoded form?
