### ISSUE TITLE
Arguments parsing problems

### ISSUE THREAD

**Issue by bartavelle** [curiefense/curiefense#248]
**Describe the bug**
There are two problems with the current argument parsing system:

 * the `iptools` rust module uses a partial function for url decoding. If the decoded value is not an utf8-encoded string, this will return a lua error, which, in turn, will produce a null pointer deref in envoy (I only tracked this problem up to [this place](https://github.com/envoyproxy/envoy/blob/5a71fc7c49641934f1529047f1fc2515145c95e0/source/extensions/filters/common/lua/lua.cc#L46) where it returns `nullptr`);
 * url decoding is performed prior to argument parsing

**To Reproduce**

On curieproxy:

 * problem 1: Get `http://localhost:30081/ddd?xx%AF`, curieproxy segfaults
 * problem 2: Get `http://localhost:30081/test/?a=1&b=2%26c=3`, three url arguments are found, `a`, `b` and `c`

**Expected behavior**

 * problem 1: No segfault
 * problem 2: there are only too arguments, `a` and `b`

Tested at commit 763acc036645a99ce75257f1bbc64cad41aa4d77

**Comment by bartavelle** [comment]
Concerning the segfault problem, I integrated `iptools` into the `curiefense` native module, and used a safe url-decoding function. It will return `nil` when the resulting value is not an utf-8 string.

It solves the segfault problem, but is less than idea as it would allow bypassing some checks.

**Comment by flaper87** [comment]
@bartavelle hey, is this still an open issue? Any updates?

**Comment by flaper87** [comment]
> @bartavelle hey, is this still an open issue? Any updates?

@bartavelle ping? :)

**Comment by bartavelle** [comment]
Should be ok now!
