### ISSUE TITLE
Manually updating profiling list using the 'update now' button does not work properly

### ISSUE THREAD

**Issue by Aviv-Galmidi** [curiefense/curiefense#25]
Reported by @tzuryby 

Change source of list profiling
Clicked 'update now' button (next to last update)
nothing shows up in the UI

**Comment by tzuryby** [comment]
I think it has to do with the parser
the list https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ipip_country/ipip_continent_af.netset provides no "annotation"
make sure the parsers get IP and "inserts" annotation if missing

**Comment by tzuryby** [comment]
@Aviv-Galmidi I removed the "doit" label which refers to a company "DoIT International" who provided feedback rather than literal "do it"  :-)

**Comment by tzuryby** [comment]
@Aviv-Galmidi what's the status of this one?

**Comment by Aviv-Galmidi** [comment]
Should be fixed in UI version 1.2.28 by PR #218 
Cannot reproduce with this version
