### ISSUE TITLE
Tag rules fail parsing IPV4 addresses from 3rd party sources

### ISSUE THREAD

**Issue by tzuryby** [curiefense/curiefense#251]
**Added new list, IPv4 did not match**

Sourec URL
https://myip.ms/files/blacklist/general/latest_blacklist.txt

Site:
https://myip.ms/browse/blacklist/Blacklist_IP_Blacklist_IP_Addresses_Live_Database_Real-time

Screenshot:
https://drive.google.com/file/d/1iOU42Wkvk8LknGOvRWALFZgYI-23TONd/view?usp=sharing

**Comment by Aviv-Galmidi** [comment]
Unassigning myself until I'd start working on the task, in case some other member of the team or a member of the community would get to it before I do
