### ISSUE TITLE
Header parser does not seems to work properly

### ISSUE THREAD

**Issue by rikatz** [curiefense/curiefense#27]
First of all, great project!!

I was following the Quick start guide, creating the Header profiling list.

While testing this, in a new install with docker-compose, the requests doesn't get tagged when using the Header validation.

I've seen that the response from the server is always with the Header with the first character capitalized (Foo), so I've tested both with capitalized and not.

Strangely, when following exactly what's in the quick start, no log even appear when this rule is created.

So I've tested with my own IP in the profiling list, and it works fine (the query gets tagged, and further I can block it), so I'm wondering if this is something with the header parsing.

Thank you!

**Comment by tzuryby** [comment]
@rikatz hi,
I was trying to reproduce with no success...

The following are 3 API calls, one create a profiling list, second is updating it, and the third simply fetch it.
Can you kindly run the following sequence against your docker-compose deployment
(obviously, replace localhost if needed)

```
curl 'http://localhost:30000/api/v1/configs/master/d/profilinglists/e/' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  --data-binary '{"id":"0ac708e43053","name":"New Profiling List","source":"self-managed","mdate":"2020-11-13T07:26:28.540Z","notes":"New List Notes and Remarks","entries_relation":"OR","active":true,"tags":[],"entries":[]}' 

curl 'http://localhost:30000/api/v1/configs/master/d/profilinglists/e/0ac708e43053/' \
  -X 'PUT' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  --data-binary '{"id":"0ac708e43053","name":"New Profiling List","source":"self-managed","mdate":"2020-11-13T07:25:06.570Z","notes":"New List Notes and Remarks","entries_relation":"OR","active":true,"tags":["test"],"entries":[["headers",["foo","bar"],"baz"]]}' 

curl 'http://localhost:30000/api/v1/configs/master/d/profilinglists/e/0ac708e43053/'
```

**Comment by rikatz** [comment]
for sure :)

```
{"ok": true}
{"ok": true}
{"id": "0ac708e43053", "name": "New Profiling List", "source": "self-managed", "mdate": "2020-11-13T07:25:06.570Z", "notes": "New List Notes and Remarks", "active": true, "entries_relation": "OR", "tags": ["test"], "entries": [["headers", ["foo", "bar"], "baz"]]}
```
And wait 1 minute :)

Now, when I run the curl pointing to the demo app:

```
date; curl http://192.168.0.10:30081/with/header -H "foo: bar"
sex 13 nov 2020 08:46:52 -03
Request served by c29cbf56942b

HTTP/1.1 GET /with/header

Host: 192.168.0.10:30081
X-Forwarded-Proto: http
X-Request-Id: b1fe4afe-c780-46db-8c0e-c40f7c71eed9
X-Envoy-Expected-Rq-Timeout-Ms: 15000
User-Agent: curl/7.68.0
Accept: */*
Foo: bar
X-Forwarded-For: 192.168.0.11
X-Envoy-Internal: true
Content-Length: 0
``` 

But in the logs:

![image](https://user-images.githubusercontent.com/7182341/99069392-0934be00-258d-11eb-99cd-1f25533960b4.png)

And just to make sure the header created with the API is there:

![image](https://user-images.githubusercontent.com/7182341/99069502-3b462000-258d-11eb-8ef2-cc26ac37da79.png)

So I've forced publishing the new rules (as far as I saw the above API calls only updates the profiling lists, right?)

And then, even if I make the call it wont get logged :/
![image](https://user-images.githubusercontent.com/7182341/99069717-ab54a600-258d-11eb-94ff-b49f59ff4d72.png)

![image](https://user-images.githubusercontent.com/7182341/99069738-b7406800-258d-11eb-8d2d-bd887b494253.png)

**Comment by rikatz** [comment]
Here's the debug output from compose: https://gist.github.com/rikatz/3fd2b00f305cb469fe9e5650c07b889a

**Comment by tzuryby** [comment]
thanks @rikatz.
new images will be pushed soon (pending QA).
