### ISSUE TITLE
Tasker completion deployment

### ISSUE THREAD

**Issue by tzuryby** [curiefense/curiefense#3]
tasker that support two types of tasks.
1. update lists
2. analyze logs

**Comment by flaper87** [comment]
@Aviv-Galmidi looks like you have attempted to work on this a couple of times. Is that correct? Is this issue still valid?

**Comment by Aviv-Galmidi** [comment]
> @Aviv-Galmidi looks like you have attempted to work on this a couple of times. Is that correct? Is this issue still valid?

I never attempted to work on this issue, I accidentally referenced this issue when tagging my commits a while back
e.g. Attempt number 3 - # followed by the number 3 in the commit message automatically linked the commit to the issue

**Comment by flaper87** [comment]
> > @Aviv-Galmidi looks like you have attempted to work on this a couple of times. Is that correct? Is this issue still valid?
> 
> I never attempted to work on this issue, I accidentally referenced this issue when tagging my commits a while back
> e.g. Attempt number 3 to fix an unrelated issue - # followed by the number 3 in the commit message automatically linked the commit to the issue

lol! that's fun! 🤣🤣🤣

I will sync with @tzuryby and @xavier-rbz on this
