### ISSUE TITLE
curiefense/curietasker:latest not found

### ISSUE THREAD

**Issue by bochuxt** [curiefense/curiefense#30]
**Describe the bug**
Pulling curietasker (curiefense/curietasker:latest)...
ERROR: manifest for curiefense/curietasker:latest not found: manifest unknown: manifest unknown

**To Reproduce**
1. Go to curiefense/deploy/compose
2. docker-compose up

Run on MacOS

**Comment by phil777** [comment]
Hello,

Sorry about the missing container. This is fixed now. 

Please try again and let us know if it solved your issue !
