### ISSUE TITLE
flow control - problem when the "path" of any request in the flow sequence is identical to the last step

### ISSUE THREAD

**Issue by bartavelle** [curiefense/curiefense#316]
**Describe the bug**
The last step has a special shortcut treatment that can incorrectly flag requests as "being the last step" while they are not.

**To Reproduce**
Create a policy that matches flows that look like:

```
http://foo/?action=step1
http://foo/?action=step2
http://foo/?action=step3
```
When calling the first URL, the proxy flags it as attempting the last step without doing the intermediate steps before.

**Expected behavior**
When calling each URL in order, the user should be cleared.

**Additional context**
The problem lies in the `validate_flow` function, where the first test:

```lua
if session_sequence_key == last_entry.key then
```

will not take into account the other parts of the query.

**Comment by bartavelle** [comment]
(Also the *host* header seems to be ignored, but I didn't test it yet)

**Comment by bartavelle** [comment]
Extra question: in the redis server, a list of strings is used, but only its length seems to be useful. Why not directly store integers? For debug purpose?

**Comment by flaper87** [comment]
@tzuryby @phil777 maybe one of you can provide some details here?

**Comment by bartavelle** [comment]
This is fixed in the rust code, and it comes with a test.

**Comment by flaper87** [comment]
> This is fixed in the rust code, and it comes with a test.

pls, link this issue in the PR that will bring in the rust code :)

**Comment by bartavelle** [comment]
Now that #385 is merged, this should work!

**Comment by flaper87** [comment]
> Now that #385 is merged, this should work!

Do we have tests for this? :smiley:

**Comment by bartavelle** [comment]
Rule : https://github.com/curiefense/curiefense/blob/main/curiefense/curieproxy/rust/luatests/config/json/flow-control.json#L11-L38
Test : https://github.com/curiefense/curiefense/blob/main/curiefense/curieproxy/rust/luatests/flows/steps.json

**Comment by flaper87** [comment]
Thanks! This is fantastic :)
