### ISSUE TITLE
[curielogger] setting a value for CURIELOGGER_OUTPUTS_ELASTICSEARCH_KIBANA_URL has no effects

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#325]
1/ Set a value for `CURIELOGGER_OUTPUTS_ELASTICSEARCH_KIBANA_URL`
2/ Observe that it still tries to contact http://kibana:5601, the value from `curielogger.yml`

**Comment by flaper87** [comment]
I think we can mark this one as obsolete given the move to using filebeat (and the goal to deprecate logstash/es outputs).
