### ISSUE TITLE
Add `AND` support in profiling lists entries relations

### ISSUE THREAD

**Issue by tzuryby** [curiefense/curiefense#33]
right now we only support "OR" relations between enties.
we must add "AND", and perhaps blocks, e.g.

```python
(
    {}
  OR
    {}
)
AND
(
    {}
  OR
    {}
)
```

**Comment by tzuryby** [comment]
@Aviv-Galmidi 
this is the structure you should expect on the UI side:
Given vue components are supported recursive rendering, you shoud be able to implement it without to much of complexity.

```JSON
{
  "entries": {
    "relation": "and",
    "entries": [
      {
        "relation": "or",
        "entries": [
          [
            "uri",
            "/login"
          ],
          [
            "uri",
            "/account"
          ]
        ]
      },
      {
        "relation": "and",
        "entries": [
          [
            "headers",
            "user-agent",
            "curl"
          ],
          [
            "headers",
            "content-type",
            "application/json"
          ]
        ]
      }
    ]
  }
}
```

**Comment by Aviv-Galmidi** [comment]
@tzuryby 

This is what I'm understanding, please correct me if something is wrong
**Client:**
Add component which contains relation and entries fields
Relation field is either 'OR' or 'AND'
entries field is either the same component (recursively) or a list of arrays describing entries (ip, headers, etc.)
**Server:**
I'm not sure what changes are needed on the server side. I've found this file "tagprofiler.lua" which refers to a list's entries_relation and it seems like this is the only place we're using it
Should I edit this file to be able to read entries_relation in the new recursive format?

**Comment by tzuryby** [comment]
I will dal with the server side to proceed in parallel.

**Comment by tzuryby** [comment]
entries are *always* list .
entries type a: list of objects, then each object contains ".relation" and ".entries" (nested)
entries type b: list of lists (actual values)

**Comment by tzuryby** [comment]
call summary
assuming 2 levels.
top level relations will appear only when there is more than one group.


```JSON
{
  "entries": {
    "relation": "and", //>> relevant only when there are multiple entries
    "entries": [
      {
        "relation": "or",
        "entries": [
          [
            "uri",
            "/login"
          ],
          [
            "uri",
            "/account"
          ]
        ]
      },
      {
        "relation": "and",
        "entries": [
          [
            "headers",
            "user-agent",
            "curl"
          ],
          [
            "headers",
            "content-type",
            "application/json"
          ]
        ]
      }
    ]
  }
}
```

**Comment by Aviv-Galmidi** [comment]
New design:
<img width="897" alt="Screen Shot 2020-11-29 at 15 29 54" src="https://user-images.githubusercontent.com/10487148/100543280-e296a880-3257-11eb-9b30-b6a20a2c8665.png">
