### ISSUE TITLE
Flow Control is not blocking out-of-order requests

### ISSUE THREAD

**Issue by spiros-p** [curiefense/curiefense#362]
Curiefense is not blocking requests that should be blocked, according to a defined Flow Control sequence.

**To Reproduce**
1. Create a Flow Control sequence, such as this one:

<img width="1066" alt="Screen Shot 2021-05-31 at 8 16 51 AM" src="https://user-images.githubusercontent.com/50348585/120213929-a7663980-c1e8-11eb-8830-b3579e2538c1.png">

2. Submit a POST request, without submitting a GET request first:

`curl -H 'Host: example.com' http://[redacted]/login --request POST `

**Expected behavior**
Curiefense should block the request, but it does not.

**Comment by bartavelle** [comment]
I think that is the correct command:

```sh
curl -X POST -H 'Host: example.com' http://[redacted]/login
```
It does work as expected, *for me*, in the Rust branch.

**Comment by bartavelle** [comment]
Oh my bad, that is the same command! Let's test it again when the Rust code is merged!

**Comment by bartavelle** [comment]
Now that #385 is merged, this should work!

**Comment by Aviv-Galmidi** [comment]
@yanushg Tagging you as it might have been missed, according to Simon this should be working now
