### ISSUE TITLE
Action in Tag rules does not work - we do not execute action 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#374]
**Describe the bug**
When choosing Actions (not tag) we do not block requests that match tag rules condition 
**To Reproduce**
1. Go to tag rules and create a new tag list with your IP as a section 
2. choose 503 response code in actions 
3. send a request we do not block 

**Expected behavior**
We should get 503 response code 
**Screenshots**

**Desktop (please complete the following information):**
Working with Curiefence on GCP instance 
 - Browser chrome
 - Version 1.3.6

**Comment by bartavelle** [comment]
I do not think there is any code supporting this feature? There certainly isn't in the Rust code, and I did not remember anything like that in the Lua code when I starting porting it. @tzuryby, is that a new feature or something I missed completely?

**Comment by bartavelle** [comment]
(also, isn't that redundant with ACLs?)

**Comment by bartavelle** [comment]
So this is a new future, and it is not redundant with ACLs :) Thanks @yanushg , I will work on this ASAP.

**Comment by bartavelle** [comment]
Now that #385 is merged, this should work.

**Comment by yanushg** [comment]
Tag rule action was implemented and working:
1. we do block requests as expected  
2. In logs we have an error in parsing Json when request is blocked by tag rule - 
Error decoding JSON: invalid character 'i' in literal true (expecting 'r')

**Comment by bartavelle** [comment]
This should help with the logging problem : https://github.com/curiefense/curiefense/pull/401
