### ISSUE TITLE
Add existing rate limit to url maps - we do not validate choosing a rate limit before adding 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#376]
**Describe the bug**
After adding the first rate limit we can add rule without choosing a rule 
**To Reproduce**
1. Go to rate limit tab and create several rate limit rules 
2. Go to url maps and attach the first rule 
3. click on + to add another existing rate limit -> dont choose a rate limit and press add 

**Expected behavior**
we should disable the option to add if nothing is chosen 
**Screenshots**
video added 

https://user-images.githubusercontent.com/48092909/122402919-98bca800-cf86-11eb-86bb-15bc3da15d53.mov

**Desktop (please complete the following information):**
 - Browser chrome 
 - Version 1.3.6

**Comment by jdorfman** [comment]
Thanks for the video @yanushg! Looking into it cc @Aviv-Galmidi

**Comment by Aviv-Galmidi** [comment]
Merged in PR #426
