### ISSUE TITLE
Same tag in ACL in all categories - Does not present an error 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#380]
**Describe the bug**
When adding the same tag in all categories we mark the entry in red but do not present any error and we can save the ACL and publish configuration 
**To Reproduce**
1. Go to ACL Profiles tab 
2. add the same tag name to all categories for example "test" 

**Expected behavior**
we should get an error that we can not enter the same tag in all categories 
**Screenshots**
screenshot added 

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 1.3.6
![Screen Shot 2021-06-20 at 14 52 39](https://user-images.githubusercontent.com/48092909/122673823-e29dcc00-d1da-11eb-808b-ac03137ee4ef.png)

**Comment by Aviv-Galmidi** [comment]
Closed in https://github.com/curiefense/curiefense/pull/427
