### ISSUE TITLE
We do not validate same record "name:value" combination in tag rules section 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#381]
**Describe the bug**
When adding a new section with 2 identical records we do not validate 
**To Reproduce**
1. go to Tag rules tab 
2. create a new section and add IP entry with 1.1.1.1 IP address 
3. add to the same section another record as the one above 

**Expected behavior**
we should validate entries in the same section 

**Screenshots**
![Screen Shot 2021-06-20 at 15 28 22](https://user-images.githubusercontent.com/48092909/122674960-ff88ce00-d1df-11eb-9137-089db7f59f84.png)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 1.3.6

**Comment by Aviv-Galmidi** [comment]
Closed in https://github.com/curiefense/curiefense/pull/416
