### ISSUE TITLE
Make `request.attributes` consistent

### ISSUE THREAD

**Issue by flaper87** [curiefense/curiefense#395]
**Describe the bug**

The current definition of `Attributes` is `map[string]interface{}`, which allows for pretty much anything to go in. This has been implemented as a flattened field in Elasticsearch in order to prevent index mapping explosions. 

This has the downside of not allowing for more specific analysis to be done since the fields are considered dynamic and they are not guaranteed to exist.

https://github.com/curiefense/curiefense/blob/d00a8ec8c2ba506b57d34ff784dc4641003d40ea/curiefense/curielogger/pkg/entities/curie_proxy_log.go#L3-L12

Considering that some of these attributes are quite static, the proposal is to identify a set of keys that are always present, modify the `Attributes` map to move the `static` attributes to the main log struct and leave the Attributes map as-is in order to be able to index dynamic attributes that are currently unknown.

This, however, needs to be aligned with the nginx effort that @bartavelle is driving so that we make sure these Attributes can be provided by all the supported proxies. 

Some common attributes:

```
{
  "query": "THE VALUE OF QUERY IS STORED AS A FLATTENED OBJECT UNDER THE ARGUMENTS FIELD",
  "ipnum": 876223070,
  "scheme": "http",
  "remote_addr": "SOME IP",
  "method": "GET",
  "path": "THERE ARE CASES WHERE PATH IS NOT SET",
  "xff_trusted_hops": 1,
  "ip": "52.58.26.94",
  "authority": "104.197.219.104:30081",
  "uri": "PATH+QUERY"
}
```

**Comment by bartavelle** [comment]
I do not emit that many attributes in the Rust code, only `uri`, `path`, `query`, `ip` and `ipnum`.
I *think* `remote_addr` is obsolete, scheme and path are not in `addr`.
