### ISSUE TITLE
Tag rules - Section values should change if we change type of entry 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#397]
**Describe the bug**
When chosen a different kind of attribute type we should change values section 
**To Reproduce**
1. go to tag rules 
2.  choose Method/path/uri 

**Expected behavior**
the value section stays the same it should be consistent to the attribute we chose - for example when we choose header type
**Screenshots**

https://user-images.githubusercontent.com/48092909/123628074-60855700-d81b-11eb-9db9-1f8f40d69eae.mov

**Comment by Aviv-Galmidi** [comment]
Closed in https://github.com/curiefense/curiefense/pull/416
