### ISSUE TITLE
Tag rules actions - Response action is not working properly 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#402]
**Describe the bug**
When we choose response and a different response code we get 200 response code 
**To Reproduce**
1. create a tag rule action with header "test:test" section and response code 300 
2. save and publish 
3. send a request with "test:test" header 

**Expected behavior**
we should get 300 response code, we get 200

**Comment by yanushg** [comment]
@bartavelle please take a look

**Comment by bartavelle** [comment]
Do you get the tag applied? If not, can you post just the corresponding tag rule/elasticsearch log? For the tag rule, there should be an url at the bottom of the ui for this tag rule, something that looks like `/conf/api/v1/configs/master/d/tagrules/e/49aea5a8d96b/
`. By prepending the beginning of the URL (something like `http://localhost:30080/`) you can get it.

**Comment by bartavelle** [comment]
Never mind I can reproduce it.
