### ISSUE TITLE
integrating curiefense with micro-front-ends such as Piral https://github.com/smapiot/piral

### ISSUE THREAD

**Issue by nathanawmk** [curiefense/curiefense#405]
I am building a micro-frontend using Piral (https://github.com/smapiot/piral) and I wish to leverage curiefense to protect my micro-frontend. Am trying to fit both together. Can anyone advise if this has been done?

**Comment by jdorfman** [comment]
Hey @nathanawmk. I'm not aware of this specific use case. I'm going to convert this to a discussion because I want to learn more about your micro-fontend.
