### ISSUE TITLE
rate limit challenge action blocks instead of challenge loop  

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#409]
**Describe the bug**
when we choose challenge action in rate limit we get access blocked instead of challenge loop 
**To Reproduce**
1.go to rate limit and create a rate limit with 1/10 limit by ip and action challenge 
2. attach to url - save and publish 

**Expected behavior**
we should get a challenge loop when we hit rate limit instead we get access denied

**Comment by yanushg** [comment]
this should fix the issue: https://github.com/curiefense/curiefense/pull/404

**Comment by bartavelle** [comment]
Should be OK now.
