### ISSUE TITLE
Rate limit redirect action does not work 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#411]
**Describe the bug**
When rate limit is configured with redirect option we do not redirect to the specified site we block 
**To Reproduce**
1. Go to rate limit and create a rate limit with redirect action and ip as attribute 
2. save and publish - send a request (in logs we can see the correct response code) 

**Expected behavior**
should redirect to site but instead we get blocked 
![Screen Shot 2021-07-05 at 7 00 38](https://user-images.githubusercontent.com/48092909/124417016-ef84f880-dd60-11eb-94f4-8570dfa02d7b.png)

**Comment by bartavelle** [comment]
There is a problem with the default text (it should say something about redirection), but can you check you used a status code that is consistent with redirection (such as 307)?

**Comment by bartavelle** [comment]
Should be OK now

**Comment by yanushg** [comment]
Well looks ok - when choosing status code 345 for example we get a message - you will be redirected 
closing the issue
