### ISSUE TITLE
When tag rule action is challenge - No access logs when request is sent from curl 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#413]
**Describe the bug**
When request is sent from curl and we configure challenge in tag rules action, we do not present the request in ES logs 
**To Reproduce**
1. Go to tag rules and create a new list -> in section choose query and challenge under action (works globally)
2. save and publish 
3. send a request using curl - this will trigger the challenge 
4. open ES 

**Expected behavior**
we do not present this requests in logs 

curl -vv "http://localhost:30081/test?yana=1"

**Comment by bartavelle** [comment]
Should be fixed by #450

**Comment by bartavelle** [comment]
Should be OK now!

**Comment by yanushg** [comment]
We actually fixed the logs and we can see the request but - blocked is marked false - didnt we decide that for challenge blocked will be true? @bartavelle @ItaiPrajgrod

**Comment by yanushg** [comment]
working on a GCP instance - no logs - @bartavelle Simon - when you have time. curie logger presents the logs

**Comment by yanushg** [comment]
Working on Maksim's env - everything works ok 
mystery
