### ISSUE TITLE
Flow control - When creating a new sequence - we have only one section instead of two 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#414]
**Describe the bug**
Flow control - When creating a new sequence - we have only one section instead of two 
**To Reproduce**
1. Go to flow control 
2. Add a new flow control and add a sequence 

**Expected behavior**
we should have 2 sections by default 

one screenshot from docs the other one from UI 
![Screen Shot 2021-07-05 at 12 35 21](https://user-images.githubusercontent.com/48092909/124450854-7fd93280-dd8d-11eb-9cdf-ff710ce671d4.png)

![Screen Shot 2021-07-05 at 12 31 38](https://user-images.githubusercontent.com/48092909/124450648-502a2a80-dd8d-11eb-98f5-02d954ff92ed.png)

**Comment by semharel** [comment]
Could not reproduce
