### ISSUE TITLE
ACL and Tag rules configuration does not allow/deny as expected 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#428]
**Describe the bug**
When tag rule has 2 tags and we assign one in allow and one in deny - we deny all 
When we create 2 different lists with same ip and assign one in allow and one in deny - we allow all 
**To Reproduce**
1. Go to Tag rules and create a list with 2 tags and ip in a section 
2. Go to ACL and add one tag to allow and other to deny -> save publish and send a request 

**Expected behavior**
Requests should be allowed - they get denied

**Comment by bartavelle** [comment]
Can you post the elasticsearch logs for the two cases? If possible, the individual configurations would help a lot too (those downloaded from an url like `/conf/api/v1/configs/master/d/tagrules/e/49aea5a8d96b/`)

**Comment by yanushg** [comment]
@bartavelle any more help with that?

**Comment by bartavelle** [comment]
Yes, I could not reproduce it, so if you can send be the exact configs you used that would be very helpful!

**Comment by yanushg** [comment]
Not repro in new version - closing
