### ISSUE TITLE
Challenge "blocked" flag should be False 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#432]
**Describe the bug**
Challenge in the system is marked "blocked=true" 

**To Reproduce**
1. Go to ACL - put tag all in Deny bot column 
2. save and publish 
3. send a request using curl 

**Expected behavior**
Should present challenge in logs and "blocked=false"

**Comment by bartavelle** [comment]
Why should it be "false" as the request was blocked? Is there some spec somewhere?

**Comment by yanushg** [comment]
The request is not blocked - it got challenged and did not passed 
In reblaze i checked and the flag is false when we fail challenge

**Comment by bartavelle** [comment]
Ah this is quite a problem to me then :) The request is indeed blocked by the filtering system, and replaced by other content (in this case the challenge), and I just reuse this in the log file. It means I will have to special case it for this I guess?

What should be the behavior with other action types (for example, redirect? I believe I currently mark it as blocked too)

**Comment by yanushg** [comment]
I am talking about Deny bot - we are using the same function for challenge in all modules?

**Comment by bartavelle** [comment]
Yes this is the same in all modules. Internally, there are the following response types:

```rust
pub enum SimpleActionT {
    Default,
    Monitor,
    Ban(Box<SimpleAction>),
    RequestHeader(HashMap<String, String>),
    Response(String),
    Redirect(String),
    Challenge,
}
```

In that list, which ones should be logged with `block=true` ?

**Comment by bartavelle** [comment]
(Default is the default blocking action)

**Comment by bartavelle** [comment]
After discussion, this seems like the desired behavior.
