### ISSUE TITLE
Rate Limits with Redirect Action does not work as expected

### ISSUE THREAD

**Issue by semharel** [curiefense/curiefense#434]
**Describe the bug**
Rate limit with a redirect action is worked only for a status code value 301 - 308, for different values the action unexpected 

**To Reproduce**
1. Go to 'Rate limits'
2. Create a new rate limit 
3. fill out name, description, Threshold = '3', TTL= '15', Count by: Attribute = IP Address, Event = HTTP request,
4.  Action = Redirect , Status code: '200' , Location = https://13news.co.il/
5. Go to 'URL Map' attach the rate limit to location, save and publish 
6. Send 4 requests to http://localhost:30081/. 

**Expected behavior**
Get Echo web server or  https://13news.co.il/

**Screenshots**

<img width="923" alt="Screen Shot 2021-07-11 at 14 11 22" src="https://user-images.githubusercontent.com/86234718/125192729-0096a380-e252-11eb-8409-8367300eaf66.png">

<img width="1128" alt="Screen Shot 2021-07-11 at 14 10 39" src="https://user-images.githubusercontent.com/86234718/125192744-1310dd00-e252-11eb-8d6e-5ce860337c1a.png">

<img width="1104" alt="Screen Shot 2021-07-11 at 14 09 43" src="https://user-images.githubusercontent.com/86234718/125192709-efe62d80-e251-11eb-9f16-2aee96c59ee4.png">

**Desktop (please complete the following information):**
 - OS: big sur
 - Browser chrome
 - Version latest

**Comment by yanushg** [comment]
Duplicate for - #411

**Comment by semharel** [comment]
duplicated
