### ISSUE TITLE
Flow control - tag action in flow control - no tag is added  

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#437]
**Describe the bug**
When sending a request to last method in flow control with tag as action we do not get the tag 
**To Reproduce**
1. Go to flow control tab and verify that the last method in default flow control is POST 
2. change the action to "tag" and send a request  curl -XPOST  

**Expected behavior**
Tag should be displayed

**Comment by bartavelle** [comment]
What is the tag expected to look like?

**Comment by bartavelle** [comment]
(something like flow:rule_id ?)

**Comment by yanushg** [comment]
Just like Rate limit tag action - just rate limit name

**Comment by bartavelle** [comment]
Should be fixed by #446

**Comment by bartavelle** [comment]
Should be OK now!

**Comment by yanushg** [comment]
@bartavelle Still no tag when choosing tag only action

**Comment by yanushg** [comment]
asn:nil, wafid:--default--, geo:nil, urlmap-entry:default, all, container:curieproxy, ip:172-22-0-1, aclid:--default--, urlmap:default-entry, bot, aclname:default-acl, wafname:default-waf, curieaccesslog
--


Tags from flow control request with tag only - attaching the flow control 
{"id": "c03dabe4b9ca", "name": "Flow Control Example", "ttl": 60, "key": [{"attrs": "ip"}], "sequence": [{"method": "POST", "uri": "/test", "cookies": {}, "headers": {"host": "http://localhost:30081"}, "args": {}}, {"method": "GET", "uri": "/test", "cookies": {}, "headers": {"host": "http://localhost:30081"}, "args": {}}], "action": {"type": "monitor"}, "include": ["all"], "exclude": [], "notes": "New Flow Control Notes and Remarks", "active": true}

**Comment by bartavelle** [comment]
I think the configuration should be `"headers": {"host": "localhost:30081"}` and not `"headers": {"host": "http://localhost:30081"}`.

**Comment by yanushg** [comment]
@bartavelle When i change this header - flow control is not working an all (no action) when i change back - all actions are working - still no tag

**Comment by bartavelle** [comment]
Can you post the corresponding elasticsearch log entries? I can't unfortunately reproduce this one :(

**Comment by yanushg** [comment]
Flow control conf: {"id": "c03dabe4b9ca", "name": "Flow Control Example", "ttl": 60, "key": [{"attrs": "ip"}], "sequence": [{"method": "POST", "uri": "/test", "cookies": {}, "headers": {"host": "http://localhost:30081"}, "args": {}}, {"method": "GET", "uri": "/test", "cookies": {}, "headers": {"host": "http://localhost:30081"}, "args": {}}], "action": {"type": "monitor"}, "include": ["all"], "exclude": [], "notes": "New Flow Control Notes and Remarks", "active": true}

Log from curielogger: 
{"timestamp":"2021-07-19T08:21:13.403165Z","blocked":false,"block_reason":null,"tags":["aclname:default-acl","urlmap-entry:default","geo:nil","container:curieproxy","wafname:default-waf","vpn","all","bot","urlmap:default-entry","aclid:--default--","asn:nil","wafid:--default--","ip:192-168-32-1","curieaccesslog"],"rx_timers":{"firstupstreambyte":"0.0024304","lastupstreambyte":"0.0025177000000000003","lastbyte":0.00006840000000000001},"tx_timers":{"firstupstreambyte":"0.0014088","lastupstreambyte":"0.0014316","firstdownstreambyte":"0.0024949","lastdownstreambyte":"0.0025671"},"upstream":{"cluster":"target_site","connectionfailure":false,"connectiontermination":false,"localaddress":"192.168.32.11","localaddressport":42226,"overflow":false,"remoteaddress":"192.168.32.10","remoteaddressport":8080,"remotereset":false,"requesttimeout":false,"retrylimitexceeded":false,"transportfailurereason":""},"downstream":{"connectiontermination":false,"directremoteaddress":"192.168.32.1","directremoteaddressport":60080,"localaddress":"192.168.32.11","localaddressport":80,"protocolerror":false,"remoteaddress":"192.168.32.1","remoteaddressport":60080},"tls":{"localcertificate":{"properties":"","propertiesaltnames":[]},"peercertificate":{"properties":"","propertiesaltnames":[]},"ciphersuite":"\u003cnil\u003e","sessionid":"","snihostname":"","version":"VERSION_UNSPECIFIED"},"request":{"requestid":"cc6ff9de-e5bf-4e88-bbb6-cd23a707059c","scheme":"http","bodybytes":0,"headersbytes":237,"headers":{"x-forwarded-proto":"http","x-envoy-internal":"true","x-request-id":"cc6ff9de-e5bf-4e88-bbb6-cd23a707059c","x-forwarded-for":"192.168.32.1","user-agent":"curl/7.64.1","accept":"*/*"},"cookies":{},"arguments":{},"geo":{"continent":{"name":null,"code":null},"country":{"iso":null,"name":null,"eu":null},"asn":null,"city":{"name":"-"},"location":{},"company":null},"attributes":{"ip":"192.168.32.1","uri":"/test","path":"/test","method":"GET"}},"response":{"bodybytes":269,"code":200,"codedetails":"via_upstream","headers":null,"headersbytes":123,"trailers":null},"metadata":{"delayinjected":false,"failedlocalhealthcheck":false,"faultinjected":false,"invalidenvoyrequestheaders":false,"localreset":false,"nohealthyupstream":false,"noroutefound":false,"ratelimited":false,"ratelimitserviceerror":false,"routename":"","samplerate":0,"streamidletimeout":false,"unauthorizeddetails":"REASON_UNSPECIFIED"}}

**Comment by yanushg** [comment]
Flow control: 
{"id": "c03dabe4b9ca", "name": "Flow Control Example", "ttl": 60, "key": [{"attrs": "ip"}], "sequence": [{"method": "POST", "uri": "/test", "cookies": {}, "headers": {"host": "localhost:30081"}, "args": {}}, {"method": "GET", "uri": "/test", "cookies": {}, "headers": {"host": "localhost:30081"}, "args": {}}], "action": {"type": "monitor"}, "include": ["all"], "exclude": [], "notes": "New Flow Control Notes and Remarks", "active": true}

Logs from curielogger: 
{"timestamp":"2021-07-19T08:35:29.181122Z","blocked":false,"block_reason":null,"tags":["ip:192-168-32-1","aclname:default-acl","wafid:--default--","wafname:default-waf","human","container:curieproxy","vpn","asn:nil","urlmap:default-entry","urlmap-entry:default","all","aclid:--default--","geo:nil","curieaccesslog"],"rx_timers":{"firstupstreambyte":"0.0034038000000000002","lastupstreambyte":"0.003504","lastbyte":0.00009790000000000001},"tx_timers":{"firstupstreambyte":"0.0016710000000000002","lastupstreambyte":"0.0017099","firstdownstreambyte":"0.0034755000000000003","lastdownstreambyte":"0.0035628"},"upstream":{"cluster":"target_site","connectionfailure":false,"connectiontermination":false,"localaddress":"192.168.32.11","localaddressport":41932,"overflow":false,"remoteaddress":"192.168.32.10","remoteaddressport":8080,"remotereset":false,"requesttimeout":false,"retrylimitexceeded":false,"transportfailurereason":""},"downstream":{"connectiontermination":false,"directremoteaddress":"192.168.32.1","directremoteaddressport":60254,"localaddress":"192.168.32.11","localaddressport":80,"protocolerror":false,"remoteaddress":"192.168.32.1","remoteaddressport":60254},"tls":{"localcertificate":{"properties":"","propertiesaltnames":[]},"peercertificate":{"properties":"","propertiesaltnames":[]},"ciphersuite":"\u003cnil\u003e","sessionid":"","snihostname":"","version":"VERSION_UNSPECIFIED"},"request":{"requestid":"126d8575-a2d5-497e-a4ca-d08a1be44d18","scheme":"http","bodybytes":0,"headersbytes":1235,"headers":{"x-forwarded-for":"192.168.32.1","accept-encoding":"gzip, deflate, br","sec-ch-ua-mobile":"?0","accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","sec-fetch-site":"same-origin","sec-fetch-mode":"no-cors","x-envoy-internal":"true","pragma":"no-cache","sec-fetch-dest":"image","sec-ch-ua":"\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"","accept-language":"en-US,en;q=0.9","x-request-id":"126d8575-a2d5-497e-a4ca-d08a1be44d18","cache-control":"no-cache","x-forwarded-proto":"http","referer":"http://localhost:30081/test","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"},"cookies":{"rbzid":"+SdUyhk+lxamJYkZff2WNjprk6e4aJYw/M6CQnAaAUvtzdIJK/N0iVFyQ+0kmu0BHjz2lyEdZZRSHkRP0qfe8SrMH3JlG8gTMI1xi4mXSzpfD5Fdt6jDrqEX5fyE2Hb4uL0Ci2Pvg2dvuAtDok3HKjPFnF6iEFhH71PEaTEsOZP3kTyuqKC4Z6E-","redirect_to":"%2Fexplore%3Fleft%3D%255B%2522now-15m%2522%252C%2522now%2522%252C%2522Prometheus%2522%252C%257B%2522expr%2522%253A%2522sum%2528rate%2528curiemetric_session_details_total%255B1m%255D%2529%2529%2Bby%2B%2528aclid%2529%2522%257D%252C%257B%2522ui%2522%253A%255Btrue%252Ctrue%252Ctrue%252C%2522none%2522%255D%257D%255D%26orgId%3D1"},"arguments":{},"geo":{"asn":null,"city":{"name":"-"},"location":{},"company":null,"continent":{"code":null,"name":null},"country":{"name":null,"eu":null,"iso":null}},"attributes":{"ip":"192.168.32.1","uri":"/favicon.ico","path":"/favicon.ico","method":"GET"}},"response":{"bodybytes":1300,"code":200,"codedetails":"via_upstream","headers":null,"headersbytes":124,"trailers":null},"metadata":{"delayinjected":false,"failedlocalhealthcheck":false,"faultinjected":false,"invalidenvoyrequestheaders":false,"localreset":false,"nohealthyupstream":false,"noroutefound":false,"ratelimited":false,"ratelimitserviceerror":false,"routename":"","samplerate":0,"streamidletimeout":false,"unauthorizeddetails":"REASON_UNSPECIFIED"}}

**Comment by yanushg** [comment]
also - when we block by flow control - blocked flag is false.

**Comment by bartavelle** [comment]
The second request was the automatic call to `favicon.ico`. As you seem to be using the nginx backend, feel free to paste the whole log, it is even more useful!

**Comment by bartavelle** [comment]
By the way this is what I get when a request is blocked (after cleaning it up a bit):

```
[info] session_nginx.lua:23: inspect(): {"user-agent":"curl\/7.68.0","host":"localhost:30082","accept":"*\/*"}, client: 172.22.0.1, server: _, request: "GET /login HTTP/1.1", host: "localhost:30082"
[debug] session_nginx.lua:50: inspect(): decision: {"action":"custom_response","logs":[{"elapsed_micros":0,"level":"debug","message":"Inspection init"},{"elapsed_micros":35,"level":"debug","message":"map_request starts"},{"elapsed_micros":58,"level":"debug","message":"headers mapped"},{"elapsed_micros":103,"level":"debug","message":"geoip computed"},{"elapsed_micros":137,"level":"debug","message":"args mapped"},{"elapsed_micros":151,"level":"debug","message":"Inspection starts (grasshopper active: true)"},{"elapsed_micros":154,"level":"warning","message":"Could not find rbzid cookie!"},{"elapsed_micros":176,"level":"debug","message":"Human check result: false"},{"elapsed_micros":212,"level":"debug","message":"Selected hostmap default entry"},{"elapsed_micros":244,"level":"debug","message":"Selected hostmap entry default"},{"elapsed_micros":502,"level":"debug","message":"request tagged"},{"elapsed_micros":606,"level":"debug","message":"challenge phase2 ignored"},{"elapsed_micros":851,"level":"debug","message":"Testing flow control Flow Control Example (step 1)"},{"elapsed_micros":863,"level":"debug","message":"Checking flow control Flow Control Example (step 1)"}],"request_map":{"args":{},"attrs":{"authority":"localhost:30082","ip":"172.22.0.1","ipnum":"2887122945","method":"GET","path":"/login","query":"","uri":"/login"},"cookies":{},"geo":{"asn":null,"city":{"name":"-"},"company":null,"continent":{"code":null,"name":null},"country":{"eu":null,"iso":null,"name":null},"location":{}},"headers":{"accept":"*/*","host":"localhost:30082","user-agent":"curl/7.68.0"},"tags":["geo:nil","urlmap-entry:default","wafid:--default--","bot","asn:nil","container:77689ae20839","aclid:--default--","aclname:default-acl","ip:172-22-0-1","urlmap:default-entry","flow-control-example","test","all","wafname:default-waf"]},"response":{"atype":"block","ban":false,"block_mode":true,"content":"curiefense - request denied","extra_tags":null,"headers":null,"reason":{"initiator":"flow_check","name":"Flow Control Example"},"status":403}}
[debug] nativeutils.lua:96: log_nginx_messages(): 0µs Inspection init
[debug] nativeutils.lua:96: log_nginx_messages(): 35µs map_request starts
[debug] nativeutils.lua:96: log_nginx_messages(): 58µs headers mapped
[debug] nativeutils.lua:96: log_nginx_messages(): 103µs geoip computed
[debug] nativeutils.lua:96: log_nginx_messages(): 137µs args mapped
[debug] nativeutils.lua:96: log_nginx_messages(): 151µs Inspection starts (grasshopper active: true)
[warn] nativeutils.lua:100: log_nginx_messages(): 154µs Could not find rbzid cookie!, client: 172.22.0.1, server: _, request: "GET /login HTTP/1.1", host: "localhost:30082"
[debug] nativeutils.lua:96: log_nginx_messages(): 176µs Human check result: false
[debug] nativeutils.lua:96: log_nginx_messages(): 212µs Selected hostmap default entry
[debug] nativeutils.lua:96: log_nginx_messages(): 244µs Selected hostmap entry default
[debug] nativeutils.lua:96: log_nginx_messages(): 502µs request tagged
[debug] nativeutils.lua:96: log_nginx_messages(): 606µs challenge phase2 ignored
[debug] nativeutils.lua:96: log_nginx_messages(): 851µs Testing flow control Flow Control Example (step 1)
[debug] nativeutils.lua:96: log_nginx_messages(): 863µs Checking flow control Flow Control Example (step 1)
[error] nativeutils.lua:82: custom_response(): {"status":403,"atype":"block","headers":null,"content":"curiefense - request denied","reason":{"name":"Flow Control Example","initiator":"flow_check"},"extra_tags":null,"ban":false,"block_mode":true}, client: 172.22.0.1, server: _, request: "GET /login HTTP/1.1", host: "localhost:30082"

{"host":"localhost","requestid":"298cec4960162be6894cc1c59d6954ab","method":"GET","metadata":{},"port":0,"block_reason":{"name":"Flow Control Example","initiator":"flow_check"},"blocked":true,"request":{"attributes":{"uri":"\/login","method":"GET","path":"\/login","query":"","ip":"172.22.0.1","authority":"localhost:30082","ipnum":"2887122945"},"originalpath":"","headers":{"user-agent":"curl\/7.68.0","host":"localhost:30082","accept":"*\/*"},"arguments":{},"cookies":{},"headersbytes":84,"bodybytes":0,"geo":{"city":{"name":"-"},"continent":{"name":null,"code":null},"asn":null,"location":{},"company":null,"country":{"eu":null,"name":null,"iso":null}}},"response":{"nxgrequestlength":"84","code":403,"headers":{"connection":"close","content-type":"application\/octet-stream","transfer-encoding":"chunked"},"codedetails":"unknown"},"downstream":{"localaddress":"172.22.0.6","remoteaddressport":59228,"directlocaladdress":"172.22.0.6","directremoteaddressport":59228,"localaddressport":30082,"remoteaddress":"172.22.0.1"},"rx_timers":{},"timestamp":"2021-07-19T08:46:54.81200003Z","path":"\/login","tx_timers":{"lastupstreambyte":"0.000"},"tls":{"peercertificate":{}},"upstream":{},"scheme":"http","tags":["geo:nil","urlmap-entry:default","wafid:--default--","bot","asn:nil","container:77689ae20839","aclid:--default--","aclname:default-acl","ip:172-22-0-1","urlmap:default-entry","flow-control-example","test","all","wafname:default-waf","curieaccesslog"]}
```
Pretty printed this looks OK "for me":

```json
{
  "block_reason": {
    "initiator": "flow_check",
    "name": "Flow Control Example"
  },
  "blocked": true,
  "downstream": {
    "directlocaladdress": "172.22.0.6",
    "directremoteaddressport": 59228,
    "localaddress": "172.22.0.6",
    "localaddressport": 30082,
    "remoteaddress": "172.22.0.1",
    "remoteaddressport": 59228
  },
  "host": "localhost",
  "metadata": {},
  "method": "GET",
  "path": "/login",
  "port": 0,
  "request": {
    "arguments": {},
    "attributes": {
      "authority": "localhost:30082",
      "ip": "172.22.0.1",
      "ipnum": "2887122945",
      "method": "GET",
      "path": "/login",
      "query": "",
      "uri": "/login"
    },
    "bodybytes": 0,
    "cookies": {},
    "geo": {
      "asn": null,
      "city": {
        "name": "-"
      },
      "company": null,
      "continent": {
        "code": null,
        "name": null
      },
      "country": {
        "eu": null,
        "iso": null,
        "name": null
      },
      "location": {}
    },
    "headers": {
      "accept": "*/*",
      "host": "localhost:30082",
      "user-agent": "curl/7.68.0"
    },
    "headersbytes": 84,
    "originalpath": ""
  },
  "requestid": "298cec4960162be6894cc1c59d6954ab",
  "response": {
    "code": 403,
    "codedetails": "unknown",
    "headers": {
      "connection": "close",
      "content-type": "application/octet-stream",
      "transfer-encoding": "chunked"
    },
    "nxgrequestlength": "84"
  },
  "rx_timers": {},
  "scheme": "http",
  "tags": [
    "geo:nil",
    "urlmap-entry:default",
    "wafid:--default--",
    "bot",
    "asn:nil",
    "container:77689ae20839",
    "aclid:--default--",
    "aclname:default-acl",
    "ip:172-22-0-1",
    "urlmap:default-entry",
    "flow-control-example",
    "test",
    "all",
    "wafname:default-waf",
    "curieaccesslog"
  ],
  "timestamp": "2021-07-19T08:46:54.81200003Z",
  "tls": {
    "peercertificate": {}
  },
  "tx_timers": {
    "lastupstreambyte": "0.000"
  },
  "upstream": {}
}
```

**Comment by yanushg** [comment]
Found the tag - sorry for the mistake
