### ISSUE TITLE
Rate limit (tag rules and flow control as well) ban action "challenge" - Does not give challenge 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#438]
**Describe the bug**
Set rate limit/tag rule/flow control with action ban and sub action challenge - we do not give challenge 
**To Reproduce**
1. Go to rate limit\tag rule\flow control create a new - set action as ban with challenge 
2. Send a request to match the rule (web and curl) 

**Expected behavior**
We should get challenge

**Comment by bartavelle** [comment]
What should be the behavior when the challenge is passed ? As it is "ban", should be pass to the next stage of filtering or always emit the challenge?

**Comment by yanushg** [comment]
for curl - challenge will never pass 
for web - if we pass challenge - return 200 

should be implemented in challenge action as well

**Comment by bartavelle** [comment]
OK, I'll wait for PR #404 to be merged and check this out.

**Comment by bartavelle** [comment]
Should be ok now!

**Comment by bartavelle** [comment]
Actually not, this should be fixed by #471.

**Comment by yanushg** [comment]
@tzuryby No ban action challenge in Flow control

**Comment by semharel** [comment]
The flow control with the challenge of Ban action return 503, but the regular challenge works 
indeed in tag rules we don't have a Ban action, and the challenge regular works

**Comment by olgasobolevsky** [comment]
Ban: challenge fixed for Flow control and Rate limits
