### ISSUE TITLE
Rate limit with tag only action - Requests that need to be tagged cannot be identified

### ISSUE THREAD

**Issue by semharel** [curiefense/curiefense#439]
**Describe the bug**
When setting a rate with tag-only action, the differences between requests that should be blocked and requests that should not be blocked cannot be identified.
Because all requests are marked with the same tag 

**To Reproduce**
1. Go to 'Rate limits'
2. Create a new rate limit
3. fill out name, description, Threshold = '3', TTL= '15', Count by: Attribute = IP Address, Event = HTTP request,
4. Action = tag-only, save 
5. attach the rate limit to location save and publish 
6. send 4 curl requests to the location 

**Expected behavior**
the 3 first requests should not be marked, and the last request should be mark as blocked, but all requests are marked the same 

**Screenshots**
<img width="1408" alt="Screen Shot 2021-07-11 at 17 14 50" src="https://user-images.githubusercontent.com/86234718/125198668-8d9a2680-e26b-11eb-972e-281181146ac5.png">

<img width="1000" alt="Screen Shot 2021-07-11 at 17 17 03" src="https://user-images.githubusercontent.com/86234718/125198743-dbaf2a00-e26b-11eb-8695-5230918830e0.png">

<img width="1067" alt="Screen Shot 2021-07-11 at 17 14 03" src="https://user-images.githubusercontent.com/86234718/125198676-9be84280-e26b-11eb-97f1-1f463f6bcd12.png">

**Desktop (please complete the following information):**
 - OS:  iOS 
 - Browser command line
 - Version  latest

**Additional context**

**Comment by bartavelle** [comment]
Is that really the expected behavior? I thought all tested rate limit should tag?

**Comment by semharel** [comment]
No, I realized that design is not like that
There should be a tag only on the blocking reason
