### ISSUE TITLE
Tags with underscore are not working

### ISSUE THREAD

**Issue by yuvalbaryochay** [curiefense/curiefense#455]
**Describe the bug**
I created a tag rule with the tag `test_01`, and matched allowed policy while traffic was blocked.

After removing the underscore, all worked.

either support underscores or prevent the UI and the API from using them.

**Comment by Aviv-Galmidi** [comment]
Re-opening so we could run QA tests to make sure it is fixed
@yanushg tagging for notice

**Comment by semharel** [comment]
It is Working
