### ISSUE TITLE
Tag rules- When creating the same query attribute in a section and deleting the first one - "create section" btn disappear  

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#459]
**Describe the bug**
Tag rules- When creating the same query attribute in a section and deleting the first one - "create section" btn disappear  
**To Reproduce**
1. create a tag rule list 
2. add a new section with query attribute 
3. in the same section create another query attribute with the same value 
4. Delete the first record 

**Expected behavior**
we should present the "create new section" btn 
**Screenshots**

![Screen Shot 2021-07-13 at 13 10 22](https://user-images.githubusercontent.com/48092909/125434780-c60f386c-01ca-48e3-993b-823cb08e1c7f.png)

**Comment by denis-reblaze** [comment]
Cannot reproduce
