### ISSUE TITLE
Tag rules validation- Header, Cookie, Attribute record type is not validated 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#461]
**Describe the bug**
Tag rules validation- Header, Cookie, Attribute record type is not validated 
**To Reproduce**
1. Create a new tag rule list 
2. Select Header/ Cookie/Attribute record type 
3. add another one with same values  
**Expected behavior**
We should validate that we can not have the same record value: name combination in same section

**Comment by denis-reblaze** [comment]
Already fixed by the code merged in https://github.com/curiefense/curiefense/pull/449
