### ISSUE TITLE
No geo location data

### ISSUE THREAD

**Issue by Freakachoo** [curiefense/curiefense#468]
Seems the `request.geo` data was lost in access logs stored in elastic search.
At the moment only `request.geo.city.name` is available but it has an empty or `-` value.

**To Reproduce**
1. Do any request to the echo server
2. See log in Kibana
3. Try to find `request.geo` - see that no data is provided, but the empty city name

**Expected behavior**
`request.geo` should contain:
```
"request": {
  ...
  "geo": {
    "city": {
      "name": "-"
    },
    "country": {
      "iso": "il",
      "name": "israel"
    },
    "company": "Partner Communications Ltd.",
    "continent": {
      "name": "asia",
      "code": "AS"
    },
    "location": {
      "lon": 34.834,
      "lat": 32.1679
    },
    "asn": 12400
  },
  ...
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5842747/125477037-82e27f43-e01e-45c6-bb14-a78baf6608c2.png)

**Comment by Freakachoo** [comment]
@flaper87 @tzuryby take a look guys, please. Possibly this is important for 1.4 version.

**Comment by flaper87** [comment]
@Freakachoo this may be related to the default `xff_trusted_hops` configured (?)

When reporting missing data in Elasticsearch, I would recommend always share logs from envoy and curielogger. This way we can see what Envoy is producing, what curielogger receives, and then what makes it to Elasticsearch.

Could you do this?

**Comment by Freakachoo** [comment]
Sure! 
<details>
 <summary>
Here is what I've got in curielogger:
</summary>
<pre>
{
  "timestamp": "2021-07-14T12:06:02.670932Z",
  "blocked": false,
  "block_reason": null,
  "tags": [
    "ip:172-29-0-1",
    "geo:nil",
    "urlmap:default-entry",
    "wafname:default-waf",
    "aclid:--default--",
    "rate-limit-example-rule-5-60",
    "urlmap-entry:default",
    "container:curieproxy",
    "aclname:default-acl",
    "asn:nil",
    "wafid:--default--",
    "bot",
    "all",
    "curieaccesslog"
  ],
  "rx_timers": {
    "firstupstreambyte": "0.0085126",
    "lastupstreambyte": "0.0086508",
    "lastbyte": 0.00013790000000000002
  },
  "tx_timers": {
    "firstupstreambyte": "0.0066908",
    "lastupstreambyte": "0.0067212",
    "firstdownstreambyte": "0.0086315",
    "lastdownstreambyte": "0.008769200000000001"
  },
  "upstream": {
    "cluster": "target_site",
    "connectionfailure": false,
    "connectiontermination": false,
    "localaddress": "172.29.0.10",
    "localaddressport": 38098,
    "overflow": false,
    "remoteaddress": "172.29.0.2",
    "remoteaddressport": 8080,
    "remotereset": false,
    "requesttimeout": false,
    "retrylimitexceeded": false,
    "transportfailurereason": ""
  },
  "downstream": {
    "connectiontermination": false,
    "directremoteaddress": "172.29.0.1",
    "directremoteaddressport": 63778,
    "localaddress": "172.29.0.10",
    "localaddressport": 80,
    "protocolerror": false,
    "remoteaddress": "172.29.0.1",
    "remoteaddressport": 63778
  },
  "tls": {
    "localcertificate": {
      "properties": "",
      "propertiesaltnames": []
    },
    "peercertificate": {
      "properties": "",
      "propertiesaltnames": []
    },
    "ciphersuite": "<nil>",
    "sessionid": "",
    "snihostname": "",
    "version": "VERSION_UNSPECIFIED"
  },
  "request": {
    "requestid": "8004b2de-455e-4b85-b085-df3119695c6a",
    "scheme": "http",
    "bodybytes": 0,
    "headersbytes": 600,
    "headers": {
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
      "referer": "http://curie.demo:30081/",
      "accept-encoding": "gzip, deflate",
      "accept-language": "en-US,en;q=0.9,ru;q=0.8",
      "x-forwarded-proto": "http",
      "x-forwarded-for": "172.29.0.1",
      "x-envoy-internal": "true",
      "cache-control": "no-cache",
      "accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
      "pragma": "no-cache",
      "x-request-id": "8004b2de-455e-4b85-b085-df3119695c6a"
    },
    "cookies": {
      "grafana_session": "56d29e74a2c62d99b1fcf26662153471"
    },
    "arguments": {},
    "geo": {
      "location": {},
      "company": null,
      "continent": {
        "code": null,
        "name": null
      },
      "country": {
        "eu": null,
        "iso": null,
        "name": null
      },
      "asn": null,
      "city": {
        "name": "-"
      }
    },
    "attributes": {
      "ip": "172.29.0.1",
      "uri": "/favicon.ico",
      "path": "/favicon.ico",
      "method": "GET"
    }
  },
  "response": {
    "bodybytes": 650,
    "code": 200,
    "codedetails": "via_upstream",
    "headers": null,
    "headersbytes": 123,
    "trailers": null
  },
  "metadata": {
    "delayinjected": false,
    "failedlocalhealthcheck": false,
    "faultinjected": false,
    "invalidenvoyrequestheaders": false,
    "localreset": false,
    "nohealthyupstream": false,
    "noroutefound": false,
    "ratelimited": false,
    "ratelimitserviceerror": false,
    "routename": "",
    "samplerate": 0,
    "streamidletimeout": false,
    "unauthorizeddetails": "REASON_UNSPECIFIED"
  }
}
</pre>
</details>


<details>
 <summary>
And here is what's in elasticsearch:
</summary>
<pre>
{
  "_index": "curieaccesslog-2021.07.14-000002",
  "_type": "_doc",
  "_id": "oKDopHoBCn955LCO8ZUA",
  "_version": 1,
  "_score": null,
  "_ignored": [
    "request.geo.location"
  ],
  "fields": {
    "agent.version.keyword": [
      "7.13.3"
    ],
    "request.headersbytes": [
      600
    ],
    "host.name.keyword": [
      "3e7cdb28d795"
    ],
    "metadata.failedlocalhealthcheck": [
      false
    ],
    "upstream.overflow": [
      false
    ],
    "docker.container.labels.com_docker_compose_service.keyword": [
      "curielogger"
    ],
    "docker.container.labels.com_docker_compose_project_config_files": [
      "docker-compose.yaml"
    ],
    "downstream.localaddress": [
      "172.29.0.10"
    ],
    "container.id": [
      "ccb103eeae311be1c665ae2e208bd688f399f4071a2162190b70b0b648ca6c31"
    ],
    "tls.peercertificate.properties.keyword": [
      ""
    ],
    "docker.container.labels.com_docker_compose_project_config_files.keyword": [
      "docker-compose.yaml"
    ],
    "upstream.localaddressport": [
      38098
    ],
    "container.image.name": [
      "curiefense/curielogger:main"
    ],
    "response.codedetails": [
      "via_upstream"
    ],
    "docker.container.labels.com_docker_compose_project.keyword": [
      "compose"
    ],
    "agent.name": [
      "3e7cdb28d795"
    ],
    "docker.container.labels.com_docker_compose_service": [
      "curielogger"
    ],
    "metadata.faultinjected": [
      false
    ],
    "request.attributes.method.keyword": [
      "GET"
    ],
    "tls.version": [
      "VERSION_UNSPECIFIED"
    ],
    "metadata.ratelimitserviceerror": [
      false
    ],
    "downstream.remoteaddress": [
      "172.29.0.1"
    ],
    "agent.id.keyword": [
      "5cabd886-dea9-4ad9-b7fd-f9fc90a36ba9"
    ],
    "input.type": [
      "container"
    ],
    "agent.hostname": [
      "3e7cdb28d795"
    ],
    "tx_timers.firstdownstreambyte.keyword": [
      "0.0086315"
    ],
    "tags": [
      "ip:172-29-0-1",
      "geo:nil",
      "urlmap:default-entry",
      "wafname:default-waf",
      "aclid:--default--",
      "rate-limit-example-rule-5-60",
      "urlmap-entry:default",
      "container:curieproxy",
      "aclname:default-acl",
      "asn:nil",
      "wafid:--default--",
      "bot",
      "all",
      "curieaccesslog"
    ],
    "agent.id": [
      "5cabd886-dea9-4ad9-b7fd-f9fc90a36ba9"
    ],
    "upstream.remotereset": [
      false
    ],
    "docker.container.labels.com_docker_compose_config-hash": [
      "4fa48c3276dc970ed3efc3e7b32a6fcde1eb392dda66f57e7a810ce9485d8086"
    ],
    "upstream.requesttimeout": [
      false
    ],
    "request.attributes.uri": [
      "/favicon.ico"
    ],
    "stream.keyword": [
      "stdout"
    ],
    "input.type.keyword": [
      "container"
    ],
    "tx_timers.lastupstreambyte.keyword": [
      "0.0067212"
    ],
    "response.headersbytes": [
      123
    ],
    "docker.container.labels.com_docker_compose_oneoff": [
      "False"
    ],
    "response.code": [
      200
    ],
    "agent.type": [
      "filebeat"
    ],
    "tx_timers.firstupstreambyte.keyword": [
      "0.0066908"
    ],
    "blocked": [
      false
    ],
    "stream": [
      "stdout"
    ],
    "docker.container.labels.com_docker_compose_config-hash.keyword": [
      "4fa48c3276dc970ed3efc3e7b32a6fcde1eb392dda66f57e7a810ce9485d8086"
    ],
    "tx_timers.firstdownstreambyte": [
      "0.0086315"
    ],
    "container.image.name.keyword": [
      "curiefense/curielogger:main"
    ],
    "request.requestid": [
      "8004b2de-455e-4b85-b085-df3119695c6a"
    ],
    "metadata.routename": [
      ""
    ],
    "agent.type.keyword": [
      "filebeat"
    ],
    "timestamp": [
      "2021-07-14T12:06:02.670Z"
    ],
    "agent.ephemeral_id.keyword": [
      "30da3881-f29d-49b3-b4f3-3ee75795ae32"
    ],
    "agent.name.keyword": [
      "3e7cdb28d795"
    ],
    "tls.snihostname": [
      ""
    ],
    "request.headers": [
      {
        "x-envoy-internal": "true",
        "x-request-id": "8004b2de-455e-4b85-b085-df3119695c6a",
        "referer": "http://curie.demo:30081/",
        "x-forwarded-proto": "http",
        "accept-language": "en-US,en;q=0.9,ru;q=0.8",
        "x-forwarded-for": "172.29.0.1",
        "cache-control": "no-cache",
        "pragma": "no-cache",
        "accept-encoding": "gzip, deflate",
        "accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
      }
    ],
    "@timestamp": [
      "2021-07-14T12:06:03.300Z"
    ],
    "metadata.localreset": [
      false
    ],
    "upstream.connectiontermination": [
      false
    ],
    "log.file.path": [
      "/var/lib/docker/containers/ccb103eeae311be1c665ae2e208bd688f399f4071a2162190b70b0b648ca6c31/ccb103eeae311be1c665ae2e208bd688f399f4071a2162190b70b0b648ca6c31-json.log"
    ],
    "upstream.connectionfailure": [
      false
    ],
    "agent.ephemeral_id": [
      "30da3881-f29d-49b3-b4f3-3ee75795ae32"
    ],
    "docker.container.labels.co_elastic_logs/ignore_decoding_error.keyword": [
      "True"
    ],
    "downstream.connectiontermination": [
      false
    ],
    "docker.container.labels.co_elastic_logs/json_add_error_key.keyword": [
      "True"
    ],
    "request.scheme": [
      "http"
    ],
    "upstream.cluster": [
      "target_site"
    ],
    "metadata.delayinjected": [
      false
    ],
    "tls.sessionid": [
      ""
    ],
    "docker.container.labels.com_docker_compose_version": [
      "1.29.1"
    ],
    "upstream.remoteaddress": [
      "172.29.0.2"
    ],
    "agent.hostname.keyword": [
      "3e7cdb28d795"
    ],
    "docker.container.labels.com_docker_compose_container-number.keyword": [
      "1"
    ],
    "docker.container.labels.co_elastic_logs/ignore_decoding_error": [
      "True"
    ],
    "response.bodybytes": [
      650
    ],
    "ecs.version.keyword": [
      "1.8.0"
    ],
    "container.name": [
      "curielogger"
    ],
    "downstream.directremoteaddressport": [
      63778
    ],
    "request.attributes.path": [
      "/favicon.ico"
    ],
    "host.name": [
      "3e7cdb28d795"
    ],
    "request.geo.city.name": [
      "-"
    ],
    "metadata.invalidenvoyrequestheaders": [
      false
    ],
    "downstream.directremoteaddress": [
      "172.29.0.1"
    ],
    "request.cookies": [
      {
        "grafana_session": "56d29e74a2c62d99b1fcf26662153471"
      }
    ],
    "rx_timers.firstupstreambyte": [
      "0.0085126"
    ],
    "metadata.streamidletimeout": [
      false
    ],
    "request.attributes.ip": [
      "172.29.0.1"
    ],
    "container.name.keyword": [
      "curielogger"
    ],
    "docker.container.labels.co_elastic_logs/json_add_error_key": [
      "True"
    ],
    "log.offset": [
      28872
    ],
    "request.attributes.method": [
      "GET"
    ],
    "rx_timers.firstupstreambyte.keyword": [
      "0.0085126"
    ],
    "metadata.ratelimited": [
      false
    ],
    "tls.peercertificate.properties": [
      ""
    ],
    "ecs.version": [
      "1.8.0"
    ],
    "tx_timers.firstupstreambyte": [
      "0.0066908"
    ],
    "agent.version": [
      "7.13.3"
    ],
    "docker.container.labels.co_elastic_logs/json_keys_under_root": [
      "True"
    ],
    "metadata.nohealthyupstream": [
      false
    ],
    "docker.container.labels.com_docker_compose_oneoff.keyword": [
      "False"
    ],
    "rx_timers.lastupstreambyte.keyword": [
      "0.0086508"
    ],
    "docker.container.labels.com_docker_compose_container-number": [
      "1"
    ],
    "tx_timers.lastdownstreambyte.keyword": [
      "0.008769200000000001"
    ],
    "docker.container.labels.com_docker_compose_version.keyword": [
      "1.29.1"
    ],
    "tx_timers.lastdownstreambyte": [
      "0.008769200000000001"
    ],
    "downstream.remoteaddressport": [
      63778
    ],
    "request.geo.city.name.keyword": [
      "-"
    ],
    "request.arguments": [
      {}
    ],
    "upstream.remoteaddressport": [
      8080
    ],
    "docker.container.labels.co_elastic_logs/enabled": [
      "True"
    ],
    "upstream.retrylimitexceeded": [
      false
    ],
    "downstream.protocolerror": [
      false
    ],
    "rx_timers.lastupstreambyte": [
      "0.0086508"
    ],
    "metadata.samplerate": [
      0
    ],
    "docker.container.labels.com_docker_compose_project_working_dir.keyword": [
      "/Users/evgeniy/Projects/curiefense/deploy/compose"
    ],
    "log.file.path.keyword": [
      "/var/lib/docker/containers/ccb103eeae311be1c665ae2e208bd688f399f4071a2162190b70b0b648ca6c31/ccb103eeae311be1c665ae2e208bd688f399f4071a2162190b70b0b648ca6c31-json.log"
    ],
    "docker.container.labels.com_docker_compose_project_working_dir": [
      "/Users/evgeniy/Projects/curiefense/deploy/compose"
    ],
    "rx_timers.lastbyte": [
      0.0001379
    ],
    "metadata.unauthorizeddetails": [
      "REASON_UNSPECIFIED"
    ],
    "metadata.noroutefound": [
      false
    ],
    "docker.container.labels.co_elastic_logs/json_keys_under_root.keyword": [
      "True"
    ],
    "docker.container.labels.com_docker_compose_project": [
      "compose"
    ],
    "tls.localcertificate.properties": [
      ""
    ],
    "upstream.localaddress": [
      "172.29.0.10"
    ],
    "tls.ciphersuite": [
      "<nil>"
    ],
    "tx_timers.lastupstreambyte": [
      "0.0067212"
    ],
    "tls.localcertificate.properties.keyword": [
      ""
    ],
    "upstream.transportfailurereason": [
      ""
    ],
    "downstream.localaddressport": [
      80
    ],
    "container.id.keyword": [
      "ccb103eeae311be1c665ae2e208bd688f399f4071a2162190b70b0b648ca6c31"
    ],
    "docker.container.labels.co_elastic_logs/enabled.keyword": [
      "True"
    ],
    "request.bodybytes": [
      0
    ]
  },
  "sort": [
    1626264363300000000
  ]
}
</pre>
</details>


Not sure how to get logs from envoy. Curieproxy container gives no logs. Would it be enough what I've posted above? ^

**Comment by flaper87** [comment]
From the curielogger log, you can see that `geo:nil` and the geo object doesn't have data. This means that curieproxy is not sending such data. My guess is that it may be related to how you are running it.

- Is it a docker-compose env in a private network?
- Are the requests coming from your laptop?

If the above is the case, no geodata will be fetched because it uses local/private IP addresses, which have no geo data in the maxmind databases. 

Could you confirm whether this is the case?

I believe there's a way to trick envoy/curieproxy by forcing the IP into the `x-forwarded-for` header. Can't remember OTOH. @xavier-rbz maybe you know?

**Comment by Freakachoo** [comment]
@flaper87 you were totally right! This was missing on the **local** docker-compose environment, but the data exists if to test on a server. Closing the issue. Sorry for the mistake.
