### ISSUE TITLE
Rate limit - Method evaluation by event does not block 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#475]
**Describe the bug**
Rate limit - when event is method and count by is set to IP we do not block requests 
**To Reproduce**
1. Go to Rate limit and create a new rate limit with "count by" IP address and event by Method- save
2. Attach to url and save 
3.  Publish 

**Expected behavior**
Requests should be blocked by method - are not blocked 
Rate limit: 
<img width="1136" alt="Screen Shot 2021-07-14 at 11 18 59" src="https://user-images.githubusercontent.com/48092909/125588487-cb360d2d-f9d7-4e30-a554-bcef5d16a157.png">

**Comment by bartavelle** [comment]
I added a test case and could not reproduce it. Did you test with 3+ distinct methods in less than 15s?

**Comment by bartavelle** [comment]
This is the PR that adds the testcase: #480
