### ISSUE TITLE
Rate limit\Tag rules 503 response code blocks with 403 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#487]
**Describe the bug**
Rate limit\Tag rules 503 response code blocks with 403 

Actions: 
1. Create a rate limit with 0/10 limit and 503 response code action 
2. attach to url /test 
3. save and publish 

Expected: 
Response code should be 503

**Comment by bartavelle** [comment]
Ah this is something I did not understand, the default action for limits should be 503.

**Comment by bartavelle** [comment]
Hum according to the UI, the default action should be to return with 503, with flow/rate limit/tag actions, but I recently changed them all to 403. What should I do?

**Comment by yanushg** [comment]
ACL should return 403 all others 503 as was before

**Comment by bartavelle** [comment]
Should WAF be like ACL?

**Comment by yanushg** [comment]
Yes 403 as well

**Comment by Aviv-Galmidi** [comment]
Assigning Simon as they're have been working on it and opened a PR already
