### ISSUE TITLE
Flow control with Challenge action does not get tagged 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#494]
**Describe the bug**
Flow control with Challenge action does not get tagged 
**To Reproduce**
1. Go to Flow control and change action to challenge: {"id": "c03dabe4b9ca", "name": "Flow Control Example", "ttl": 60, "key": [{"headers": "test"}], "sequence": [{"method": "POST", "uri": "/TEST", "cookies": {}, "headers": {"host": "34.141.23.207:30081/"}, "args": {}}, {"method": "GET", "uri": "/TEST", "cookies": {}, "headers": {"host": "34.141.23.207:30081/"}, "args": {}}], "action": {"type": "response", "params": {"status": "305", "content": "loveisallyouneed"}}, "include": [], "exclude": [], "notes": "New Flow Control Notes and Remarks", "active": true}
2. Save and publish 

**Expected behavior**
We should tag with flow control name 

log fron curielogger: 

curielogger      | {"timestamp":"2021-07-20T06:54:24.140684Z","blocked":true,"block_reason":{"reason":"challenge","initiator":"phase01","tags":{}},"tags":["aclname:default-acl","urlmap:default-entry","vpn","tor","test","wafname:default-waf","aclid:--default--","container:curieproxy","wafid:--default--","yana","ip:31-154-168-166","urlmap-entry:default","tag","geo:israel","bot","","challenge-phase01","all","asn:12400","curieaccesslog"],"rx_timers":{"firstupstreambyte":"0","lastupstreambyte":"0","lastbyte":0.000051673000000000005},"tx_timers":{"firstupstreambyte":"0","lastupstreambyte":"0","firstdownstreambyte":"0.0016655720000000001","lastdownstreambyte":"0.0016909300000000002"},"upstream":{"cluster":"","connectionfailure":false,"connectiontermination":false,"overflow":false,"remotereset":false,"requesttimeout":false,"retrylimitexceeded":false,"transportfailurereason":""},"downstream":{"connectiontermination":false,"directremoteaddress":"31.154.168.166","directremoteaddressport":50345,"localaddress":"172.22.0.10","localaddressport":80,"protocolerror":false,"remoteaddress":"31.154.168.166","remoteaddressport":50345},"tls":{"localcertificate":{"properties":"","propertiesaltnames":[]},"peercertificate":{"properties":"","propertiesaltnames":[]},"ciphersuite":"\u003cnil\u003e","sessionid":"","snihostname":"","version":"VERSION_UNSPECIFIED"},"request":{"requestid":"b0b5efe8-c214-4492-8545-4648f83c7166","scheme":"http","bodybytes":0,"headersbytes":235,"headers":{"accept":"*/*","x-request-id":"b0b5efe8-c214-4492-8545-4648f83c7166","test":"yana","x-forwarded-for":"31.154.168.166","x-forwarded-proto":"http","x-envoy-external-address":"31.154.168.166","user-agent":"curl/7.64.1"},"cookies":{},"arguments":{},"geo":{"country":{"iso":"il","name":"israel","eu":null},"company":"Partner Communications Ltd.","continent":{"code":"AS","name":"asia"},"location":{"lat":32.1679,"lon":34.834},"asn":12400,"city":{"name":"-"}},"attributes":{"ip":"31.154.168.166","uri":"/test1","path":"/test1","method":"GET"}},"response":{"bodybytes":110798,"code":247,"codedetails":"lua_response","headers":null,"headersbytes":286,"trailers":null},"metadata":{"delayinjected":false,"failedlocalhealthcheck":false,"faultinjected":false,"invalidenvoyrequestheaders":false,"localreset":false,"nohealthyupstream":false,"noroutefound":false,"ratelimited":false,"ratelimitserviceerror":false,"routename":"","samplerate":0,"streamidletimeout":false,"unauthorizeddetails":"REASON_UNSPECIFIED"}}

**Comment by bartavelle** [comment]
There is an empty tag, which is *very* fishy. Would you have the nginx log lines available?

It should have lines like `Checking flow control Flow Control Example (step 1)`.

**Comment by bartavelle** [comment]
The request you pasted does not have the right path (`"uri": "/test1"`), the rule you pasted mentions `/TEST`.

**Comment by yanushg** [comment]
Even worse - cause i do get challenge on all matches "test*" (no other components are active just flow control) 
http://34.141.23.207:30080/

**Comment by yanushg** [comment]
curielogger      | {"timestamp":"2021-07-20T07:34:47.708596Z","blocked":true,"block_reason":{"reason":"challenge","initiator":"phase01","tags":{}},"tags":["challenge-phase01","yana","tag","container:curieproxy","urlmap:default-entry","urlmap-entry:default","aclname:default-acl","aclid:--default--","tor","wafname:default-waf","all","bot","ip:31-154-168-166","wafid:--default--","test","geo:israel","asn:12400","vpn","","curieaccesslog"],"rx_timers":{"firstupstreambyte":"0","lastupstreambyte":"0","lastbyte":0.000054278000000000004},"tx_timers":{"firstupstreambyte":"0","lastupstreambyte":"0","firstdownstreambyte":"0.0020122960000000002","lastdownstreambyte":"0.002038343"},"upstream":{"cluster":"","connectionfailure":false,"connectiontermination":false,"overflow":false,"remotereset":false,"requesttimeout":false,"retrylimitexceeded":false,"transportfailurereason":""},"downstream":{"connectiontermination":false,"directremoteaddress":"31.154.168.166","directremoteaddressport":60313,"localaddress":"172.22.0.10","localaddressport":80,"protocolerror":false,"remoteaddress":"31.154.168.166","remoteaddressport":60313},"tls":{"localcertificate":{"properties":"","propertiesaltnames":[]},"peercertificate":{"properties":"","propertiesaltnames":[]},"ciphersuite":"\u003cnil\u003e","sessionid":"","snihostname":"","version":"VERSION_UNSPECIFIED"},"request":{"requestid":"84b37ecd-2d44-4a74-82de-44cd5e051b77","scheme":"http","bodybytes":0,"headersbytes":234,"headers":{"x-forwarded-proto":"http","accept":"*/*","test":"yana","x-request-id":"84b37ecd-2d44-4a74-82de-44cd5e051b77","x-forwarded-for":"31.154.168.166","x-envoy-external-address":"31.154.168.166","user-agent":"curl/7.64.1"},"cookies":{},"arguments":{},"geo":{"country":{"iso":"il","name":"israel","eu":null},"company":"Partner Communications Ltd.","continent":{"name":"asia","code":"AS"},"location":{"lat":32.1679,"lon":34.834},"asn":12400,"city":{"name":"-"}},"attributes":{"ip":"31.154.168.166","uri":"/TEST","path":"/TEST","method":"GET"}},"response":{"bodybytes":110798,"code":247,"codedetails":"lua_response","headers":null,"headersbytes":286,"trailers":null},"metadata":{"delayinjected":false,"failedlocalhealthcheck":false,"faultinjected":false,"invalidenvoyrequestheaders":false,"localreset":false,"nohealthyupstream":false,"noroutefound":false,"ratelimited":false,"ratelimitserviceerror":false,"routename":"","samplerate":0,"streamidletimeout":false,"unauthorizeddetails":"REASON_UNSPECIFIED"}}

The correct URL /TEST

**Comment by yanushg** [comment]
Repro only in my env

**Comment by ItaiPrajgrod** [comment]
Fixed according to @yanushg
