### ISSUE TITLE
Tag Rules adds an empty tag to each request 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#495]
**Describe the bug**
ACL adds an empty tag to each request 
**To Reproduce**
1. Go to ACL tab 
2. Create an empty tag and save 
3. publish 
4. send a request 

ACL conf looks ok: {"id": "__default__", "name": "default-acl", "allow": [], "allow_bot": [], "deny_bot": [], "bypass": [], "deny": [], "force_deny": []}

**Expected behavior**
No tag should be added we add an empty tag 

"tags": ["aclname:default-acl", "urlmap:default-entry", "vpn", "tor", "test", "wafname:default-waf", "aclid:--default--", "container:curieproxy", "wafid:--default--", "yana", "ip:31-154-168-166", "urlmap-entry:default", "tag", "geo:israel", "bot", "", "challenge-phase01", "all", "asn:12400", "curieaccesslog"],

**Comment by bartavelle** [comment]
Is that the acl, or is there a tagging rule with an empty tag?

**Comment by bartavelle** [comment]
If you have `jq` installed, you can do something like that to check it quickly:

```bash
curl http://localhost:30080/conf/api/v1/configs/master/d/tagrules/ | jq -S '.[].tags'
```

**Comment by yanushg** [comment]
I do have an empty tag in tag rules - but this is weird because we have a UI validation 
[
  "vpn",
  "bot",
  "tag",
  "test",
  "yana",
  "tor",
  ""
]
BTW it appears twice in tag rules tags - i have only one list with those tags

**Comment by Aviv-Galmidi** [comment]
Editing the title to better reflect the issue - Tag Rule is adding the extra empty tag and not the ACL

**Comment by Aviv-Galmidi** [comment]
Changing milestone 1.4.0 -> 1.4.1 which is set as the next release as 1.4.0 has been released last night

**Comment by semharel** [comment]
Steps to reproduce the behavior:
create a new Tag rule 
in the tags field to write: "api"
      ->  without the  " ,  but add a space at the end of the tag 

action: 503 
in create new section : Header , key= test, val= tag
<img width="263" alt="Screen Shot 2021-07-29 at 12 23 26" src="https://user-images.githubusercontent.com/86234718/127469477-fa3ef1c4-e917-446c-b86a-54dd14e832b8.png">
save and publish 
send a request:  curl -H "test: tag" "http://{$HOST:PORT}/"
go to kibana :in the tags filed in  the request log  appear  2 tags "api" and " "

**Comment by Aviv-Galmidi** [comment]
The bug is related to Tag Rules, which sometimes enabled the addition of empty tags to the tags input field
Clear steps to reproduce:
1. Create a new Tag Rule
2. Type the following string into the `Tags` field in said Tag Rule "api " (note: including the whitespace)
3. Save
4. The Tag Rule has been saved with the following tag "api" and "" (empty tag) which casuses each request which matches the Tag Rule rules to have both tags added to it "api" and ""

The PR #510 fixes this bug, but is awaiting approval before merging
