### ISSUE TITLE
Tag rule lists tags - we create tags twice for the same list 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#500]
**Describe the bug**
Tag rule lists tags - we create tags twice for the same list 
**To Reproduce**
1. Create a tag list with several tags 
2. Save and publish 
3. Run curl http://localhost:30080/conf/api/v1/configs/master/d/tagrules/ | jq -S '.[].tags'
**Expected behavior**
We present the same tags twice 

output from my run: 

[
  "vpn",
  "bot",
  "tag",
  "test",
  "yana",
  "tor",
  ""
]
[
  "vpn",
  "bot",
  "tag",
  "test",
  "yana",
  "tor",
  ""
]

**Comment by Aviv-Galmidi** [comment]
Can't reproduce
I've followed the steps and the system only creates a single new Tag Rules list for me. I've downloaded all the Tag Rules to make sure and indeed there is only 1 new Tag Rule entity

Does this only happen after you publish or beforehand as well? The curl command you sent goes to the git data so it shouldn't be affected by publishing

**Comment by yanushg** [comment]
Cant repro. Not before publish or  after publish
