### ISSUE TITLE
Flow control - will blocks the request even though the active checkbox is unchecked

### ISSUE THREAD

**Issue by semharel** [curiefense/curiefense#501]
**Describe the bug**
the flow control will block the request even though the active checkbox is unchecke

**To Reproduce**
1. Go to 'flow control'
2. create a flow control 
3. checkbox 'active' mark to deactivate 

**Expected behavior**
the flow control needs not blocked the request 

**configuration**
{"id": "a3f48b4cc343", "name": "flow-control-2", "ttl": 60, "key": [{"attrs": "ip"}], "sequence": [{"method": "GET", "uri": "/login", "cookies": {}, "headers": {"host": "34.89.236.110:30081"}, "args": {}}, {"method": "POST", "uri": "/login", "cookies": {}, "headers": {"host": "34.89.236.110:30081"}, "args": {}}], "action": {"type": "default"}, "include": ["all"], "exclude": [], "notes": "New Flow Control Notes and Remarks", "active": false}

**log**
{"timestamp":"2021-07-20T12:39:48.677082Z","blocked":true,"block_reason":{"name":"flow-control-2","initiator":"flow_check"},"tags":["aclid:--default--","wafid:--default--","wafname:default-waf","flow-control-2","asn:12400","ip:31-154-168-166","container:curieproxy","bot","api","geo:israel","all","aclname:default-acl","urlmap:default-entry","urlmap-entry:default","curieaccesslog"],"rx_timers":{"firstupstreambyte":"0","lastupstreambyte":"0","lastbyte":0.000059028000000000005},"tx_timers":{"firstupstreambyte":"0","lastupstreambyte":"0","firstdownstreambyte":"0.0016359690000000001","lastdownstreambyte":"0.001670789"},"upstream":{"cluster":"","connectionfailure":false,"connectiontermination":false,"overflow":false,"remotereset":false,"requesttimeout":false,"retrylimitexceeded":false,"transportfailurereason":""},"downstream":{"connectiontermination":false,"directremoteaddress":"31.154.168.166","directremoteaddressport":53488,"localaddress":"172.24.0.10","localaddressport":80,"protocolerror":false,"remoteaddress":"31.154.168.166","remoteaddressport":53488},"tls":{"localcertificate":{"properties":"","propertiesaltnames":[]},"peercertificate":{"properties":"","propertiesaltnames":[]},"ciphersuite":"\u003cnil\u003e","sessionid":"","snihostname":"","version":"VERSION_UNSPECIFIED"},"request":{"requestid":"12ca1bd8-493d-4422-924c-ba900c3b81e8","scheme":"http","bodybytes":0,"headersbytes":228,"headers":{"x-forwarded-for":"31.154.168.166","accept":"*/*","x-forwarded-proto":"http","x-envoy-external-address":"31.154.168.166","x-request-id":"12ca1bd8-493d-4422-924c-ba900c3b81e8","user-agent":"curl/7.71.1"},"cookies":{},"arguments":{},"geo":{"continent":{"name":"asia","code":"AS"},"location":{"lat":32.1679,"lon":34.834},"asn":12400,"city":{"name":"-"},"company":"Partner Communications Ltd.","country":{"eu":null,"iso":"il","name":"israel"}},"attributes":{"ip":"31.154.168.166","uri":"/login","path":"/login","method":"POST"}},"response":{"bodybytes":27,"code":403,"codedetails":"lua_response","headers":null,"headersbytes":90,"trailers":null},"metadata":{"delayinjected":false,"failedlocalhealthcheck":false,"faultinjected":false,"invalidenvoyrequestheaders":false,"localreset":false,"nohealthyupstream":false,"noroutefound":false,"ratelimited":false,"ratelimitserviceerror":false,"routename":"","samplerate":0,"streamidletimeout":false,"unauthorizeddetails":"REASON_UNSPECIFIED"}}
**
**Screenshots**

![Screen Shot 2021-07-20 at 14 02 57](https://user-images.githubusercontent.com/86234718/126313511-84c2f95b-c419-443b-9d80-0b3d4d92f411.png)

![Screen Shot 2021-07-20 at 13 10 54](https://user-images.githubusercontent.com/86234718/126306638-d8422022-e375-4e66-8dea-a2c557d94e7f.png)

![Screen Shot 2021-07-20 at 13 06 30](https://user-images.githubusercontent.com/86234718/126307967-f0516256-3db1-4fe0-a4e4-c1b9707c6d79.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser curl

**Comment by yanushg** [comment]
Please add config

**Comment by bartavelle** [comment]
I can reproduce.

**Comment by bartavelle** [comment]
Should be ok now

**Comment by flaper87** [comment]
closing, PR went in
