### ISSUE TITLE
Flow control "Count by" - We do not count by the selected attribute   

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#503]
**Describe the bug**
Flow control "Count by" - We do not count by the selected attribute  
**To Reproduce**
1. Go to Flow control and change the count by to "header" - "test" 
2. save and publish 
3. Sent a request without the header - still gets blocked 

**Expected behavior**
The request should be blocked only if matches the evaluation 

Flow control conf: 
{"id": "c03dabe4b9ca", "name": "Flow Control Example", "ttl": 60, "key": [{"headers": "test"}], "sequence": [{"method": "POST", "uri": "/login", "cookies": {}, "headers": {"host": "35.234.114.192:30081"}, "args": {}}, {"method": "GET", "uri": "/login", "cookies": {}, "headers": {"host": "35.234.114.192:30081"}, "args": {}}], "action": {"type": "default"}, "include": [], "exclude": [], "notes": "New Flow Control Notes and Remarks", "active": true}

response: 
*   Trying 35.234.114.192...
* TCP_NODELAY set
* Connected to 35.234.114.192 (35.234.114.192) port 30081 (#0)
> GET /login HTTP/1.1
> Host: 35.234.114.192:30081
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< x-curiefense: response
< content-length: 27
< date: Tue, 20 Jul 2021 11:29:45 GMT
< server: envoy

**Comment by yanushg** [comment]
logs: 


block_reason.initiator | flow_check
-- | --
  | block_reason.name | Flow Control Example
  | blocked | true

**Comment by bartavelle** [comment]
Hum there is a strange formatting to the logs!

If the header is absent, it is handled as if it was empty, so all clients with an absent header will be handled in the same group. I expected this to be the right behavior, but does a missing key should result in the block action being taken?

**Comment by yanushg** [comment]
if the header is absent we do not count so it should not be blocked - please lets hear from itai about it

**Comment by ItaiPrajgrod** [comment]
@yanushg , @bartavelle this is a priority for 1.4.

**Comment by bartavelle** [comment]
Alright!
