### ISSUE TITLE
Flow control- Leaving the method empty is not validated 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#504]
**Describe the bug**
Flow control- Leaving the method empty is not validated 
**To Reproduce**
1. Go to flow control and erase the method of the last sequence in the section 
2.save and publish 

**Expected behavior**
We should validate that the Method can not be empty 

Flow control conf: 
{"id": "c03dabe4b9ca", "name": "Flow Control Example", "ttl": 60, "key": [{"attrs": "ip"}], "sequence": [{"method": "POST", "uri": "/login", "cookies": {}, "headers": {"host": "35.234.114.192:30081"}, "args": {}}, {"method": "GET", "uri": "/login", "cookies": {}, "headers": {"host": "35.234.114.192:30081"}, "args": {}}, {"method": "", "uri": "/login", "cookies": {}, "headers": {"host": "35.234.114.192:30081"}, "args": {}}], "action": {"type": "default"}, "include": [], "exclude": [], "notes": "New Flow Control Notes and Remarks", "active": true}

**Comment by yanushg** [comment]
Also about the Method of the first sequence in section - WE STILL BLOCK - even thought we have no flow

**Comment by tzuryby** [comment]
@Aviv-Galmidi can we verify the JSON schema vaildation for the API  and make sure there is a full coverage of tests for this?
Perhaps a team member can assists with this

**Comment by Aviv-Galmidi** [comment]
Currently we don't have a strong validation in the API nor the GUI other than types
A complete validation for both the GUI and API was planned for 1.5.0 with the addition of better error (API validation error) display in the GUI

I don't think it's a critical issue as there is a workaround of simply typing the data correctly, it is not ideal and the API/GUI should block invalid data but there is no loss of functionality with this

I can allocate time for this issue specifically to be done in 1.4.1 but the complete validation process would take more time
