### ISSUE TITLE
Rate limit - with Threshold = 0 does't added the tag to  tags list of kibana logs

### ISSUE THREAD

**Issue by semharel** [curiefense/curiefense#506]
**Describe the bug**
when created rate limit by 0 threshold, and we send a  request that is blocked by it.  the tag is not added to the tags list Elastic

**To Reproduce**
1. Go to 'rate limit'
2. create a rate limit with a 0 threshold, and count by : IP address . save and attach it to the location 
3. send a request to the system  
4. the rate limit tag doesn't appear in the tags list 

**logs**
{"timestamp":"2021-07-20T13:50:35.079826Z","blocked":true,"block_reason":{"limitname":"0-threshold-rate","initiator":"limit","key":"A87B85E944478DE7448A4F5A4C7E6482"},"tags":["aclname:default-acl","bot","geo:israel","aclid:--default--","ip:31-154-168-166","urlmap-entry:default","block-get-tag","wafid:--default--","all","asn:12400","urlmap:default-entry","wafname:default-waf","container:curieproxy","curieaccesslog"],"rx_timers":{"firstupstreambyte":"0","lastupstreambyte":"0","lastbyte":0.000052855},"tx_timers":{"firstupstreambyte":"0","lastupstreambyte":"0","firstdownstreambyte":"1.907885751","lastdownstreambyte":"1.907931396"},"upstream":{"cluster":"","connectionfailure":false,"connectiontermination":false,"overflow":false,"remotereset":false,"requesttimeout":false,"retrylimitexceeded":false,"transportfailurereason":""},"downstream":{"connectiontermination":false,"directremoteaddress":"31.154.168.166","directremoteaddressport":55032,"localaddress":"172.24.0.10","localaddressport":80,"protocolerror":false,"remoteaddress":"31.154.168.166","remoteaddressport":55032},"tls":{"localcertificate":{"properties":"","propertiesaltnames":[]},"peercertificate":{"properties":"","propertiesaltnames":[]},"ciphersuite":"\u003cnil\u003e","sessionid":"","snihostname":"","version":"VERSION_UNSPECIFIED"},"request":{"requestid":"c046d8ee-ca9e-4598-b8ff-1c57a28562c2","scheme":"http","bodybytes":0,"headersbytes":227,"headers":{"x-request-id":"c046d8ee-ca9e-4598-b8ff-1c57a28562c2","user-agent":"curl/7.71.1","x-forwarded-for":"31.154.168.166","accept":"*/*","x-forwarded-proto":"http","x-envoy-external-address":"31.154.168.166"},"cookies":{},"arguments":{},"geo":{"location":{"lat":32.1679,"lon":34.834},"asn":12400,"city":{"name":"-"},"company":"Partner Communications Ltd.","country":{"eu":null,"iso":"il","name":"israel"},"continent":{"name":"asia","code":"AS"}},"attributes":{"ip":"31.154.168.166","uri":"/login","path":"/login","method":"GET"}},"response":{"bodybytes":27,"code":403,"codedetails":"lua_response","headers":null,"headersbytes":90,"trailers":null},"metadata":{"delayinjected":false,"failedlocalhealthcheck":false,"faultinjected":false,"invalidenvoyrequestheaders":false,"localreset":false,"nohealthyupstream":false,"noroutefound":false,"ratelimited":false,"ratelimitserviceerror":false,"routename":"","samplerate":0,"streamidletimeout":false,"unauthorizeddetails":"REASON_UNSPECIFIED"}}

**Expected behavior**
the tag should appear in the tags field of  this request 

**Desktop (please complete the following information):**
 - OS: unix
 - Browser curl

**Comment by bartavelle** [comment]
Should be ok now

**Comment by flaper87** [comment]
Closing as PR went in
