### ISSUE TITLE
Host header does not appear in logs  

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#515]
**Describe the bug**
When we set the event in rate limit to Host header it does not appear in logs 
**To Reproduce**
1. Go to Rate limit and create a new rate limit with count by Header:foo and Attribute:yana add Event as header - Host and save 
2. Attach to url map 
3. Save and publish 

**Expected behavior**
We should see the header in logs 

Log from curielogger: 
`curielogger      | {"timestamp":"2021-07-25T08:33:08.168422Z","blocked":true,"block_reason":{"limitname":"Testing URL ","initiator":"limit","key":"E15A1BD93CB851A0E45136A26FB0B862"},"tags":["bot","asn:12400","container:curieproxy","urlmap:testing-url","aclid:--default--","urlmap-entry:test","ip:31-154-168-166","trusted","aclname:default-acl","wafid:--default--","wafname:default-waf","testing-url-","geo:israel","all","curieaccesslog"],"rx_timers":{"firstupstreambyte":"0","lastupstreambyte":"0","lastbyte":0.000130617},"tx_timers":{"firstupstreambyte":"0","lastupstreambyte":"0","firstdownstreambyte":"0.001595302","lastdownstreambyte":"0.0016433130000000002"},"upstream":{"cluster":"","connectionfailure":false,"connectiontermination":false,"overflow":false,"remotereset":false,"requesttimeout":false,"retrylimitexceeded":false,"transportfailurereason":""},"downstream":{"connectiontermination":false,"directremoteaddress":"31.154.168.166","directremoteaddressport":63075,"localaddress":"172.20.0.8","localaddressport":80,"protocolerror":false,"remoteaddress":"31.154.168.166","remoteaddressport":63075},"tls":{"localcertificate":{"properties":"","propertiesaltnames":[]},"peercertificate":{"properties":"","propertiesaltnames":[]},"ciphersuite":"\u003cnil\u003e","sessionid":"","snihostname":"","version":"VERSION_UNSPECIFIED"},"request":{"requestid":"811ad100-1e53-4142-8d4a-fd4da4501230","scheme":"http","bodybytes":0,"headersbytes":227,"headers":{"x-envoy-external-address":"31.154.168.166","accept":"*/*","x-request-id":"811ad100-1e53-4142-8d4a-fd4da4501230","x-forwarded-proto":"http","foo":"bar","bar":"fo","x-forwarded-for":"31.154.168.166","user-agent":"curl/7.64.1"},"cookies":{},"arguments":{},"geo":{"location":{"lon":34.834,"lat":32.1679},"asn":12400,"city":{"name":"-"},"company":"Partner Communications Ltd.","country":{"eu":null,"iso":"il","name":"israel"},"continent":{"code":"AS","name":"asia"}},"attributes":{"ip":"31.154.168.166","uri":"/test","path":"/test","method":"GET"}},"response":{"bodybytes":27,"code":503,"codedetails":"lua_response","headers":null,"headersbytes":90,"trailers":null},"metadata":{"delayinjected":false,"failedlocalhealthcheck":false,"faultinjected":false,"invalidenvoyrequestheaders":false,"localreset":false,"nohealthyupstream":false,"noroutefound":false,"ratelimited":false,"ratelimitserviceerror":false,"routename":"","samplerate":0,"streamidletimeout":false,"unauthorizeddetails":"REASON_UNSPECIFIED"}}`

URL Map conf: {"id": "ab2bd6559081", "name": "Testing URL", "match": "yana.test", "map": [{"name": "test", "match": "/test", "acl_profile": "__default__", "acl_active": false, "waf_profile": "__default__", "waf_active": false, "limit_ids": ["2b467f1c4642"]}]} 

Curl :curl -vv http://35.234.114.192:30081/test?yana=1  -H "host:yana.test" -H "foo:bar"

**Comment by tzuryby** [comment]
already fixed. 
it is attribute goes by the name of authority (http2 matter).
will be merged soon.

**Comment by tzuryby** [comment]
fixed in 1.4.

**Comment by yanushg** [comment]
Could you elaborate exactly on which version this is fixed? I’ve tested it again in 1.4.0 and I’m still reproducing the bug @tzuryby
