### ISSUE TITLE
WAF Inspection Refining 

### ISSUE THREAD

**Issue by tzuryby** [curiefense/curiefense#517]
## Path as entity next to H/C/A (headers, cookies, arguments):
Path (the uri part without the query) should be added to the WAF inspection while maintaining 
 - min risk level
 - exclude signatures

## Encoding Related

Given the input

```
'; drop table users --
```

- Dual Encoding is currently not handled. Should be. 
  - e.g. 
    - `%2527%253B%2520drop%2520table%2520users%2520--`
    
- Other encodings such as:
  - HTML Entity (`&#xXX` and `&#xXXXX`)
    - `&#x27;&#x3B;&#x20;&#x64;&#x72;&#x6F;&#x70;&#x20;&#x74;&#x61;&#x62;&#x6C;&#x65;&#x20;&#x75;&#x73;&#x65;&#x72;&#x73;&#x20;&#x2D;&#x2D;`
  - &#DDDD;
    - `&#39;&#59;&#32;&#100;&#114;&#111;&#112;&#32;&#116;&#97;&#98;&#108;&#101;&#32;&#117;&#115;&#101;&#114;&#115;&#32;&#45;&#45;`
  - \uXXXX `\u0027\u003B\u0020\u0064\u0072\u006F\u0070\u0020\u0074\u0061\u0062\u006C\u0065\u0020\u0075\u0073\u0065\u0072\u0073\u0020\u002D\u002D`
  - \UXXXXXXXX `\U00000027\U0000003B\U00000020\U00000064\U00000072\U0000006F\U00000070\U00000020\U00000074\U00000061\U00000062\U0000006C\U00000065\U00000020\U00000075\U00000073\U00000065\U00000072\U00000073\U00000020\U0000002D\U0000002D`
  - Base64 (avaialble in a branch by Simon)
    - `JzsgZHJvcCB0YWJsZSB1c2VycyAtLQ==`

## JSON structure as an Example

```
[
  {
    "id": "__default__",
    "name": "default waf",
    "cookies": {
      "min_risk": 4,
      "max_count": 2048,
      "max_length": 4096,
      "decoding": {
        "base64": true,
        "dual": true,
        "html": true,
        "unicode": true,
        "codecs": [
          "utf8"
        ]
      },
      "names": [],
      "regex": [
        {
          "key": ".+",
          "reg": "",
          "restrict": false,
          "mask": false,
          "exclusions": {
            "libinjection": 1
          }
        }
      ]
    },
    "headers": {
      "min_risk": 4,
      "max_count": 2048,
      "max_length": 4096,
      "decoding": {
        "base64": true,
        "dual": true,
        "html": true,
        "unicode": true,
        "codecs": [
          "utf8"
        ]
      },
      "names": [
        {
          "key": "accept",
          "reg": ".+",
          "restrict": false,
          "mask": false,
          "exclusions": {}
        }
      ],
      "regex": [
        {
          "key": ".+",
          "reg": "",
          "restrict": false,
          "mask": false,
          "exclusions": {
            "libinjection": 1
          }
        },
        {
          "key": "x-zebra-.*",
          "reg": ".+",
          "restrict": false,
          "mask": false,
          "exclusions": {}
        }
      ]
    },
    "args": {
      "min_risk": 4,
      "max_count": 2048,
      "max_length": 4096,
      "decoding": {
        "base64": true,
        "dual": true,
        "html": true,
        "unicode": true,
        "codecs": [
          "utf8"
        ]
      },
      "names": [
        {
          "key": "cgid",
          "reg": "",
          "restrict": false,
          "mask": false,
          "exclusions": {
            "100151": 1
          }
        },
        {
          "key": "utm_term",
          "reg": "",
          "restrict": false,
          "mask": false,
          "exclusions": {
            "100151": 1
          }
        },
        {
          "key": "flightnumbers",
          "reg": "",
          "restrict": false,
          "mask": false,
          "exclusions": {
            "100151": 1
          }
        },
        {
          "key": "__VIEWSTATE",
          "reg": ".+",
          "restrict": false,
          "mask": false,
          "exclusions": null
        }
      ],
      "regex": [
        {
          "key": "__EVENT[A-Z]+$",
          "reg": ".+",
          "restrict": false,
          "mask": false,
          "exclusions": null
        },
        {
          "key": "ctl\\d\\d[\\$_].+",
          "reg": ".+",
          "restrict": false,
          "mask": false,
          "exclusions": null
        }
      ]
    },
    "path": {
      "min_risk": 1,
      "decoding": {
        "base64": true,
        "dual": true,
        "html": true,
        "unicode": true,
        "codecs": [
          "utf8"
        ]
      },
      "exclusions": {
        "100151": 1
      }
    },
    "ignore_alphanum": true
  }
]
```
## LibInjection integration 
When blocked by libinjection block reason value shows `SQLi`

should show:
    `libinjection/SQLi/${ACTUAL_VALUE}`

**Comment by bartavelle** [comment]
Also support:

    <DIV STYLE="background-image:\0075\0072\006C\0028'\006a\0061\0076\0061\0073\0063\0072\0069\0070\0074\003a\0061\006c\0065\0072\0074\0028.1027\0058.1053\0053\0027\0029'\0029">

**Comment by bartavelle** [comment]
All selected transformations are to be applied, in a hardcoded order. The decoded value (if decoding works) will replace the previous value.

Note: this will alter the request information structure that is used for logging, it will no longer contain the original data, but the decoded data. I think this is OK as the original data will be read in the uri and body elements.

**Comment by bartavelle** [comment]
There is a problem with the current base64 code : right now it always succeeds (except for invalid length), which means that almost  all alphanumeric arguments, cookies, etc. turn into mush.

If I make it succeed only when it is decoded as a valid utd-8 string, then it might be trivial to bypass. Alternative solutions are per section/argument settings?

**Comment by bartavelle** [comment]
For example, with this uri:

    /a/b/%20c?xa%20=12&bbbb=12%28&cccc&b64=YXJndW1lbnQ%3D

the `xa ` argument turns into `�`.

**Comment by bartavelle** [comment]
Another solution is to keep the original value, and add a `:decoded` value

**Comment by tzuryby** [comment]
Not sure what do you mean by "blocking"

```
/a/b/%20c?xa%20=12&bbbb=12%28&cccc&b64=YXJndW1lbnQ%3D
```

seems to be decoded as (URL)

```
/a/b/ c?xa =12&bbbb=12(&cccc&b64=YXJndW1lbnQ=
```

the param b64 which provided as:
```
YXJndW1lbnQ=
```

should be decoded as
```
argument
```

Can you please elaborate?

**Comment by bartavelle** [comment]
The problem is with the other arguments, where we end up with:

    {"bbbb": "12(", "b64": "argument", "cccc": "", "xa ": "�"}

**Comment by bartavelle** [comment]
Does "dual" mean "urlencode + urlencode", or "each encoding, twice"?

**Comment by bartavelle** [comment]
I updated the `waf_risk_level` branch, which currently supports:

  * html entities (this will need some major work, it reuses a library that fails on the first error, unlike for example PHP's function that just ignore errors, see [the library description](https://docs.rs/htmlescape/0.3.1/htmlescape/fn.decode_html.html)). It supports `&amp;`, `&#x2e;`, `&#32;`
  * 16/32bits unicode characters, ie. `\u0020`, `\0020`, `\U00000020`
  * base64

I am writing tests right now

**Comment by denis-reblaze** [comment]
@bartavelle @tzuryby What are the supposed values for the `codecs` array? Any string or ...?

**Comment by bartavelle** [comment]
I don't know, but right now it is ignored and I only use `utf-8` ...
