### ISSUE TITLE
ACL Policies `Deny Bot` and `Allow Bot` are both being checked when ACL is not active

### ISSUE THREAD

**Issue by Aviv-Galmidi** [curiefense/curiefense#519]
**Describe the bug**
ACL Policies `Deny Bot` is being checked when ACL attached to a URL map entry but is not active 

**To Reproduce**
Deny Bot - Steps to reproduce the behavior:
1. Go to `Tag Rules`
2. Create a new Tag Rule
3. The tag rule should add tag `testing` to all requests with method GET
4. Go to `ACL Policies`
5. Create a new ACL Policy
6. Add tag `testing` to `Deny Bot`
7.  Save
8. Go to `URL Maps`
9. Connect the newly created ACL to a URL Map entry
10. Set the ACL to be inactive
11. Save
12. Publish changes
13. Send GET request to the URL provided at step 5 in the URL Map entry
14. The request is challenged - Expected not to be challenged

Allot Bot - Steps to reproduce the behavior:
1. Go to `Tag Rules`
2. Create a new Tag Rule
3. The tag rule should add tag `testing` to all requests with method GET
4. Go to `ACL Policies`
5. Create a new ACL Policy
6. Add tag `testing` to `Deny Bot` and `Allow Bot`
7.  Save
8. Go to `URL Maps`
9. Connect the newly created ACL to a URL Map entry
10. Set the ACL to be inactive
11. Save
12. Publish changes
13. Send GET request to the URL provided at step 5 in the URL Map entry
14. The request is not challenged

**Expected behavior**
Sending a request to the provided URL (from the URL Map entry on step 5) should pass without going through the ACL
From my understanding in the current reblaze product we apply `Deny Bot` even when the ACL is not active, if that is the desired case then we should update our documentations

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser Chrome
 - Version 91

Edit: was thinking of splitting this into two issues but decided against it

**Comment by tzuryby** [comment]
This is not a bug rather by design.
