### ISSUE TITLE
Flow control - Ban action response returns 503 instead of selected response code 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#520]
**Describe the bug**
Flow control - Ban action response returns 503 instead of selected response code 
**To Reproduce**
1. Go to Flow control create a Flow control with ban action with response - choose 300 response code and test as response body 
2. Save and publish 

**Expected behavior**
We should get 300 response code and response body - we get 503 response code and the selected response body

**Comment by bartavelle** [comment]
I can reproduce. I found what I think is another problem, if after being banned you can still perform the "flow" and end up with the page being served!

**Comment by bartavelle** [comment]
Status issue should be fixed with #602
