### ISSUE TITLE
Swagger API - Missing a payload field In a several Post and Put Methods

### ISSUE THREAD

**Issue by semharel** [curiefense/curiefense#521]
**Describe the bug**
These methods can't use by swagger because they miss the payload field for add new 

POST  /configs/{config}/d/{document}/e/
PUT /configs/{config}/d/{document}/e/{entry}/
PUT /configs/{config}/d/{document}/e/{entry}/

**To Reproduce example**
1. Go to '.API'
2. Click on PUT '/configs/{config}/d/{document}/e/{entry}/'

**Expected behavior**
we should be able to edit/add the entry 

**Desktop (please complete the following information):**
 - OS:Big Sur
<img width="1001" alt="Screen Shot 2021-07-27 at 15 07 14" src="https://user-images.githubusercontent.com/86234718/127151173-2bf98243-ed15-4729-bb55-c3301a52f8e8.png">

<img width="914" alt="Screen Shot 2021-07-27 at 15 11 28" src="https://user-images.githubusercontent.com/86234718/127151410-317e64c2-d655-43aa-aa8d-d6fdf64cfa03.png">

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tzuryby** [comment]
When POST body is required, use curl or other tools. Not swagger UI

**Comment by kubixcloud** [comment]
> When POST body is required, use curl or other tools. Not swagger UI

Swagger and OpenAPI has a a lot of integrations and tools like creating server/client SDKs. When the Swagger specification is not fully compatible with the API, it is not easy to use such tools and integrate on the the API.

You might consider producing a swagger specification compatible with the API in your roadmap.

Best regards,
