### ISSUE TITLE
WAF Policies mask feature is not masking the data in the logs

### ISSUE THREAD

**Issue by Aviv-Galmidi** [curiefense/curiefense#526]
**Describe the bug**
When creating a WAF Policy with a mask constraint we do not mask the data in the logs

**To Reproduce**
1. Go to `WAF Policies`
2. Create a new WAF Policy
3. Add a new header constraint with `name = foo` and `value = bar` and set it to mask the data by checking the `mask?` checkbox
4. Save
5. Go to `URL Maps`
6. Connect the newly created WAF to a URL Map entry
7. Set the WAF to be active
8. Save
9. Publish changes
10. Send a request with header `foo: bar` to the URL provided at step 5 in the URL Map entry
11. Go into Kibana logs
12. The header value should be masked, but it is displayed as plain text

The steps are written for headers, but the masking is not working for headers/cookies/arguments

**Expected behavior**
The masked paramater value should be masked in the logs

**Screenshots**
WAF settings: <img width="1082" alt="Screen Shot 2021-07-28 at 10 56 19" src="https://user-images.githubusercontent.com/10487148/127287642-21b3ebf0-04dc-441a-a523-0a1a0f46d59c.png">
Logs: <img width="932" alt="Screen Shot 2021-07-28 at 11 09 14" src="https://user-images.githubusercontent.com/10487148/127287653-dde135c1-acb0-4ebb-b02a-f9a5324dec2a.png">

**Comment by bartavelle** [comment]
* should masking always occur when the *name* matches, or only if the value also matches? I figure that for things like credit card numbers, it should be masked even with a typo.
 * there is the problem of "derived" values, for example:
   - if an url argument is to be masked, should the path be masked too? I would expect not, as this would be in the web server log anyway
   - if a base64-decoded argument matches, should the original argument be masked too? I would expect not, as it is easy to write a rule to mask it too

**Comment by bartavelle** [comment]
It has been implemented in #491
