### ISSUE TITLE
Grafana Username Password - https://docs.curiefense.io/installation/getting-started-with-curiefense

### ISSUE THREAD

**Issue by nathanawmk** [curiefense/curiefense#527]
Hi! I am planning to present curiefense during a security meetup session in Singapore. I setup it on my local docker and when I go Grafana it prompts for a Username Password. Any idea what is the username password?

 https://docs.curiefense.io/installation/getting-started-with-curiefense

**Comment by Aviv-Galmidi** [comment]
As described in the docs [here](https://docs.curiefense.io/analytics/grafana): The default username and password are `admin` and `admin`

**Comment by jdorfman** [comment]
@nathanawmk I will close this issue, for now, please reopen if you are still having issues.

Feel free to join our [Slack](https://join.slack.com/t/curiefense/shared_invite/zt-nc8lyrjo-JJoY2mwrqNOfkmoA6ycTHg) if you want to chat about the meet up. We would like to set you up for success. =)
