### ISSUE TITLE
Access Log URL

### ISSUE THREAD

**Issue by nathanawmk** [curiefense/curiefense#532]
I cant find access log https://github.com/curiefense/curiefense-gitbook/blob/main/.gitbook/assets/access-logs.png  in my cureifense setup. where is the access log?

![image](https://user-images.githubusercontent.com/14244560/127898099-24b11688-f300-4abb-8a79-04473832596c.png)

**Comment by jdorfman** [comment]
Hey @nathanawmk,

You are looking at the Curiefense config version history. For access logs You need to access Kibana (`http://localhost:5601/app/discover#/`)

Then click: Save > Share > Generate

![Image 2021-08-02 at 1 40 13 PM](https://user-images.githubusercontent.com/398230/127921074-9ce1e683-314b-4d6d-9c62-36db01af272a.jpg)

The CSV will look like this:

![Image 2021-08-02 at 1 44 08 PM](https://user-images.githubusercontent.com/398230/127921473-e7fa016a-110c-40ce-9b2e-e32c080468ec.jpg)

Let me know if that works or not.

**Comment by spiros-p** [comment]
Hi @nathanawmk,

We recently changed our logs over to Kibana. The documentation doesn't fully reflect this change yet, but is being updated as we speak. 

I'll post a message here when the update is complete, which should be soon. Thanks for your patience, and I apologize for the confusion on this.

**Comment by jdorfman** [comment]
@nathanawmk I'm going to close this issue, feel free to reopen it if these answers did not solve your problem.
