### ISSUE TITLE
Where is the "Access Log" in https://docs.curiefense.io/installation/getting-started-with-curiefense

### ISSUE THREAD

**Issue by nathanawmk** [curiefense/curiefense#534]
Where is the "Access Log" in https://docs.curiefense.io/installation/getting-started-with-curiefense? I am planning to demo this but I cannot see the Access Log.

I am from Singapore and I want to demo Curiefense so please help here

![image](https://user-images.githubusercontent.com/14244560/127899744-c0a8856f-2e19-4439-baba-61aa4c8738b2.png)

**Comment by jdorfman** [comment]
Duplicate of #532
