### ISSUE TITLE
Tag rule ui takes tags from first list 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#566]
**Describe the bug**
when creating a tag rule via api the ui takes tag from the first list 
**To Reproduce**
1. go to API 
2. Create a new tag rule with tag "test" 
3. open tag rule you have created in the UI 

**Expected behavior**
Should take the correct tag test but instead takes "api" tag

**Comment by Aviv-Galmidi** [comment]
Can be re-tested, should be fixed now
