### ISSUE TITLE
Question - deployment advice on bare-metal k8s cluster

### ISSUE THREAD

**Issue by rohrit** [curiefense/curiefense#600]
Hello,

Do you have any best practices to follow for deployment on a bare-metal k8s cluster specifically regarding the local storage bucket where the configuration is stored? what is the recommended way to replicate the configuration information to all nodes of the cluster to provide HA. Any help would be greatly appreciated.

**Comment by flaper87** [comment]
I'm sorry for the late reply. I hope you got some answers in curiefense's slack. At a high level, it's recommended to use some object store. A few options are minio, ceph, and swift. They all can be stored on-prem and they are supported by the storage libraries used in curiefense.

Hope this helps
