### ISSUE TITLE
Build Rust Failed: error: failed to run custom build command for `hyperscan-sys v0.2.2`

### ISSUE THREAD

**Issue by bochuxt** [curiefense/curiefense#605]
**Describe the bug**
When build rust lib under the rust folder, build failed as following
 Error: please download and install hyperscan from https://www.hyperscan.io/

  Caused by:
      `"pkg-config" "--libs" "--cflags" "libhs"` did not exit successfully: exit status: 1
      --- stderr
      Package libhs was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libhs.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libhs' found
      
warning: build failed, waiting for other jobs to finish..

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bartavelle** [comment]
Any update? :)

**Comment by flaper87** [comment]
@bochuxt this issue seems to be staled. I'm going to close it for now but feel free to re-open it if needed.
