### ISSUE TITLE
Secure a CII Best Practices Badge and add to README

### ISSUE THREAD

**Issue by caniszczyk** [curiefense/curiefense#62]
https://bestpractices.coreinfrastructure.org/en

**Comment by jdorfman** [comment]
@tzuryby I need this access request approved in order to continue

![Image 2021-01-06 at 4 31 10 PM](https://user-images.githubusercontent.com/398230/103836078-d367ff00-503c-11eb-94ca-18d63e5f4e21.jpg)

**Comment by jdorfman** [comment]
Once we get the ID we can just switch it 
![image](https://user-images.githubusercontent.com/398230/103838122-1e841100-5041-11eb-96ff-cb3a191e3714.png)

**Comment by jdorfman** [comment]
Thanks @caniszczyk, @tzuryby and I got this added. At this time progress is `17%`. I will be working on getting Curiefense CII Best Practices certified.
