### ISSUE TITLE
Flow control - The Ban action does not last for the full period of time set

### ISSUE THREAD

**Issue by semharel** [curiefense/curiefense#629]
**Describe the bug**
Doing an action that violates the flow control, the ban action does not block the last item for the duration of time specified

**To Reproduce**

1. Go to 'Flow control'
2. Create new
3. Setup the time frame  to 30 sec
4. Set the Count by to Attribute, IP Address
5. set the Action to Ban with 90 sec  while the Ban action is Response 
6. Denote a sequence with 2 items 
7. send a request that appropriates to the last item in the sequence 
8. send a request that appropriates to the first item in the seq 
9. send a request that appropriates to the last item again within 90 sec from step number 7 

**Expected behavior**
The request relevant to the last item in the sequence must be blocked during the time defined by the ban

**Actual  behavior**

It appears that the time during of the Ban action has no effect on the blocking action  

**Screenshots**

![Screen Shot 2021-11-23 at 13 10 54](https://user-images.githubusercontent.com/86234718/143014315-e956f72f-1436-4a8a-a3a7-5ac8b806c48c.png)

![Screen Shot 2021-11-23 at 13 14 55](https://user-images.githubusercontent.com/86234718/143014687-7724ec7e-e376-48db-b8f7-8aae3db9ff7e.png)

**Desktop (please complete the following information):**
 - OS: MacOs Monterey 
 - Browser Chrom

**Comment by bartavelle** [comment]
Currently, banning does not have any lasting effects with flow control, as it was unclear what its semantics were. For example, it is unclear if all steps should be blocked, or merely the last one. I think there were other issues but I don't remember them at the moment :/

**Comment by bartavelle** [comment]
Banning should be ok now, remains the timer reset issue.

**Comment by bartavelle** [comment]
Should be fixed by c1c5a47b9c952370c914592ca84fc762f0a11804.
