### ISSUE TITLE
Tests test_ratelimit_scope_tags_* fail

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#64]
Version: ba04fdd

To reproduce on a minikube deployment:
```
export IP=$(minikube ip); pytest --log-level INFO --base-protected-url http://$IP:30081 --base-conf-url http://$IP:30000/api/v1/ --base-ui-url http://$IP:30080 -k 'test_ratelimit_scope_tag' .
```

Observed error logs for queries associated to this test:
```
[Envoy (Epoch 0)] [2020-12-21 14:02:04.194][33][error][lua] [external/envoy/source/extensions/filters/http/lua/lua_filter.cc:600] script log: ./lua/limit.lua:41: subject has no topointer method
```

**Comment by tzuryby** [comment]
Error:
> [Envoy (Epoch 0)] [2020-12-21 14:02:04.194][33][error][lua] [external/envoy/source/extensions/filters/http/lua/lua_filter.cc:600] script log: ./lua/limit.lua:41: subject has no topointer method

Sourced by
https://rrthomas.github.io/lrexlib/manual.html
See Notes #6 in this page.

patched with lua type check.
will soon replace with hyperscan anyway

**Comment by xavier-rbz** [comment]
Still fails as of e46a52ae9ff03e9bd0449ae8f948d033cc061af8

Observed error logs for queries associated to this test: none

Incoming queries have the proper `asn:1239` tag that this test relies on.

**Comment by xavier-rbz** [comment]
The feature has been removed. Test removed in fa1eb45eaef0eca4d148839bd57866ec7b9aae85.
