### ISSUE TITLE
Rate limits not working in openresty installation

### ISSUE THREAD

**Issue by mmib** [curiefense/curiefense#642]
**Describe the bug**
Rate limits does not take any action with openresty

**To Reproduce**
1. Did docker installation, made rules and managed it to work
2. Copied all config json files from Config machine to /config/current/config/json/

Content filters working as it should but rate limits do not work.

**Server:**
 - OS: Ubuntu 20.04
 - Browser Chrome, Firefox

Can it be related with redis somehow? Noticed redis lua conf is empty now, but some quick memory storage neded to handle rate limits. Tried to install redis-server but no connections to it

**Comment by mmib** [comment]
Will answer to myself :)
Looked at https://github.com/curiefense/curiefense/blob/main/curiefense/curieproxy/rust/curiefense/src/redis.rs and found it use "REDIS_HOST" variable.

Added `REDIS_HOST="localhost"` it to /etc/environment but this not solved the issue (maybe i did something wrong).
So, edited file above 

` //let server = std::env::var("REDIS_HOST").unwrap_or_else(|_| "redis".to_string());
    //let manager = RedisConnectionManager::new(format!("redis://{}:6379/", server))?;
    let manager = RedisConnectionManager::new("redis://localhost")?;
`
cargo build and voila, it now works!

Let's add necessary changes to documentation

**Comment by bartavelle** [comment]
It is not obvious that the content of `/etc/environment` is used when you are running the service. How is it executed? If it is from systemd, perhaps you can edit the unit to add it directly. Obviously, editing the source works too ;)

**Comment by mmib** [comment]
Yep :) In any case would be good to mention redis server installation in docs.

**Comment by bartavelle** [comment]
Yes it definitely needs documenting. Thanks for spotting it!

**Comment by jdorfman** [comment]
@mmib @bartavelle [added this](https://docs.curiefense.io/installation/deployment-first-steps/nginx) to the docs

![Image 2021-12-20 at 2 52 44 PM](https://user-images.githubusercontent.com/398230/146843406-709c81e8-37c3-42d3-bdb1-9a8b12697819.jpg)

**Comment by jdorfman** [comment]
We are in the process of moving the docs to Docusaurus so anyone can easily edit the docs. Should be available in January.

**Comment by thansk** [comment]
> We are in the process of moving the docs to Docusaurus so anyone can easily edit the docs. Should be available in January.

Which January?
