### ISSUE TITLE
In acl profile when adding tag with auto complete it gets duplicated

### ISSUE THREAD

**Issue by saarbe** [curiefense/curiefense#649]
In acl profile when adding tag using the auto complete the tag gets duplicated.

1. Navigate to ACL profiles and choose any profile
2. under each category add a tag using auto complete
3.  under a category click the + button to add a tag input the 1 or 2 letters of the tag name.
4. once the tag appears in the auto complete list click the down arrow to choose it and click enter.
5. see screen recording
 
https://user-images.githubusercontent.com/96769853/147548237-1e494b62-5fa2-4c36-92b0-2ede2b8ebc1d.mov
 

**Expected behavior**
the tag is added ok 

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser chrome
 - Version 1.4.0

**Comment by Aviv-Galmidi** [comment]
Adding clarification

The bug isn't exactly a duplicated tag being added to the list
When selecting the tag from the dropdown autocomplete we should clear the field (the bug - the field is not being cleared)
When we the input field loses focus, we add the tag listed in it to the list, but as the field wasn't cleared it contains the same tag we just added, which causes it to be added twice

**Comment by olgasobolevsky** [comment]
The same bug at Flow Control Policies -> add tag to Include/Exclude.
