### ISSUE TITLE
Test test_non_allowlisted_value_norestrict_wafmatch_excludesig[params-regex-no_ignore_alphanum] fails

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#65]
Version: 11577746dc8c23b1bda4094dfa9000e192f0a649

To reproduce on a minikube deployment:
```
export IP=$(minikube ip); pytest --log-level INFO --base-protected-url http://$IP:30081 --base-conf-url http://$IP:30000/api/v1/ --base-ui-url http://$IP:30080 -k 'test_non_allowlisted_value_norestrict_wafmatch_excludesig[params-regex-no_ignore_alphanum]' .
```
Observed error logs for queries associated to this test: none

If I follow the diagram on the [documentation](https://docs.curiefense.io/console/document-editor/waf-profiles) correctly, this query should follow this path:

* the `regex-norestrict` argument has a defined contraint
* the value it receives, `htaccess`, does NOT match the Matching Value pattern `[v]+[a]{1}l?u*e`
* WAF Signatures (now "WAF Rules") are evaluated, except rule 100140 which is in "Exclude Sigs"
* The "outcome of the evaluation" should be PASS; it is fail.
* The access log page shows that this request has matched `sig_id          100140`; it has the `wafsig:100140` tag, even though it should not have been evaluated

=> This request is rejected, but should not be

![2020-12-21-154437_981x286_scrot](https://user-images.githubusercontent.com/73547485/102791689-b3331180-43a7-11eb-9bce-6b8989eaeea8.png)
![2020-12-21-154425_787x749_scrot](https://user-images.githubusercontent.com/73547485/102791695-b3cba800-43a7-11eb-989b-5881e039f016.png)

**Comment by tzuryby** [comment]
Fixed.
regex for alpha num was incorrect (missing "+") for multiple cahractares.

**Comment by tzuryby** [comment]
Got to the bottom of this issue -- introduced since we switched to hyperscan

As we did so, we now scanning all entries (values of Headers, cookeis and arguments) at once passing a single table of values. Given that, we cannot tell which arg matched when matching is returend, hence unable to check against arg's exclusion list.

I will look further into this since it is critical.

**Comment by tzuryby** [comment]
Fixed!
