### ISSUE TITLE
Security policy second added rate limit is not enforced

### ISSUE THREAD

**Issue by saarbe** [curiefense/curiefense#650]
**Describe the bug**
When adding 2 rate limit rules to security policy the second rule that was added is not enforced.
**To Reproduce**
1. configure 2 rate limit rules
2. Rule A with time frame of 30 sec and count by header (any value) with threshold 3 and action 503 service unavailable
3. Rule B with time frame of 30 sec and count by header (a different value) with threshold 4 and action response with any values
4. both rules will check by http request event.
5. in your security policy add both rules. add rule a first and rule b second
6. publish the changes
7. sent requests the meets rule A - verify traffic is blocked according to the threshold
8. sent requests the meets rule B - verify traffic is blocked according to the threshold

rule B traffic is not blocked. When adding rule B first and rule A second to security policy rule A traffic is not blocked. 

Seems that when adding 2 rukes only the first rule that is added is enforced. 

**Desktop (please complete the following information):**
 - OS: Mac os
 - Browser chrome
 - Version 1.4.0

**Additional context**
[saar.csv](https://github.com/curiefense/curief
[logger.log](https://github.com/curiefense/curiefense/files/7788501/logger.log)
ense/files/7788483/saar.csv)
[saar.csv.zip](https://github.com/curiefense/curiefense/files/7788505/saar.csv.zip)

**Comment by bartavelle** [comment]
Could reproduce, looking at it.

**Comment by bartavelle** [comment]
PR submitted :)
