### ISSUE TITLE
rate limit not working (following documented steps) on main

### ISSUE THREAD

**Issue by ldemailly** [curiefense/curiefense#658]
**Describe the bug**
Following the steps on docs https://docs.curiefense.io/installation/getting-started-with-curiefense

the acl and tagging works, the rate limit (5/min) doesn't trigger/works

**To Reproduce**
https://docs.curiefense.io/installation/getting-started-with-curiefense

or simpler:
start from scratch
go to UI Security Policies
Rate Limit Rules
"attach an existing rule"
pick 5/60 one
click add
click save
go to publish changes and click publish

run the 1s curl... get 200 all the way

**Expected behavior**
Get 503 after 5 200s

**Screenshots**

![image](https://user-images.githubusercontent.com/3664595/148156884-d31bb222-365c-4cd3-899f-469af7d02ea9.png)

**Desktop (please complete the following information):**
Tried same on mac os, wls2, and finally a VM with ubuntu 21.04

**Comment by flaper87** [comment]
@Freakachoo IIRC you recently touched the ratelimit bits. Could you take a look?

**Comment by Freakachoo** [comment]
@flaper87  I've found the reason. This line:
https://github.com/curiefense/curiefense/blob/main/curiefense/curieproxy/rust/curiefense/src/limit.rs#L98
By default config we have RL `include` tag "blocklist".

So by the code it checks that `include` is not empty and it does not contain "blocklist" tag - so the function returns false and limit being skipped.

So, this is the reason.
Possibly at least we need to remove "blocklist" from the default config.
https://github.com/curiefense/curiefense/blob/main/curiefense/images/confserver/bootstrap/confdb-initial-data/master/config/json/limits.json#L15
It should be like in Flow Control:
```
        "exclude": [],
        "include": ["all"],
```
Right?

**Comment by Freakachoo** [comment]
@ldemailly hi! Try to change `include` and `exclude` settings of the Rate Limit.
I think it suppose to be:
```
        "exclude": [],
        "include": ["all"],
```

**Comment by ldemailly** [comment]
That fixed it thank you (probably want to fix it also in the sample rule for everyone else following the instructions)

Where can I read about the design/implementation of the feature? (for instance how does it works across multiple ingress pods and aggregates/split quotas etc...)

Also possible suggestion to add e2e/doc tests (so it doesn't break unnoticed like that)

**Comment by Freakachoo** [comment]
@spiros-p it was not a blank "include" that prevented RL from occurring. The problem was that "include" had "blocklist" tag.
If "include" and "exclude" are empty - RL working well. I've tested.

**Comment by spiros-p** [comment]
@Freakachoo, yes thanks. My comment above has been corrected.

**Comment by flaper87** [comment]
@Freakachoo does https://github.com/curiefense/curiefense/pull/660 fix this issue?

**Comment by Freakachoo** [comment]
@flaper87 yes, correct

**Comment by flaper87** [comment]
Thanks for confirming! Closing now
