### ISSUE TITLE
User can create Rate Limits that will not do anything, with no warning

### ISSUE THREAD

**Issue by spiros-p** [curiefense/curiefense#659]
**Describe the bug**
The user can define a Rate Limit (RL) that will not be applied to incoming traffic. The user will not be warned about this.

**More information**

If either of these conditions apply:

- The RL's **Include** column includes a tag assigned to unwanted traffic (which by default is `blocklist`, although the user might define others as well)
- The RL's **Exclude** column includes `all`

... then the RL will not be applied to many or all of the incoming requests.

**Expected behavior**

The user should be warned when defining a RL that includes `blocklist`, or excludes `all`.

**Comment by olgasobolevsky** [comment]
New rate limit is created with Include: blocklist by default. So the RL will not be applied on many or all of the incoming requests.
<img width="1440" alt="new rate limit" src="https://user-images.githubusercontent.com/56600129/159417593-831212ee-847b-41a8-bf64-246726a2d553.png">

**Comment by olgasobolevsky** [comment]
New rate limit has tag "all" in include, exclude empty.
