### ISSUE TITLE
Entering 20 characters long string (or longer) in acl profile make it comes out from screen border

### ISSUE THREAD

**Issue by saarbe** [curiefense/curiefense#662]
Entering 20 characters long string (or longer) acl profile make it comes out from screen border

1. Navigate to ACL profiles
2. In deny section add an ipv6 address to deny

**Expected behavior**
long string is contained within the border of the screen
**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser chrome
 - Version 1.4.0

<img width="1280" alt="Screen Shot 2022-01-09 at 16 55 14" src="https://user-images.githubusercontent.com/96769853/148687692-ddcd7383-84f8-4114-bfd9-e7038f408fec.png">

**Comment by olgasobolevsky** [comment]
On laptop screen. 
Entering 20 characters long string (or longer) as tag in acl profile make the "remove" option unavailable.
<img width="1238" alt="acl profile 20 ch tag" src="https://user-images.githubusercontent.com/56600129/150672418-570b43c6-04d2-4084-a9e2-16866074be69.png">
