### ISSUE TITLE
Security Policies - Match regex with "or" (|) isn't allowed

### ISSUE THREAD

**Issue by olgasobolevsky** [curiefense/curiefense#667]
1. Create new Security profile, Delete the name at the "Match names" field.
The example for "Match names" shows regex with or condition:
(api|service).company.(io|com)
<img width="1238" alt="security policy match regex example" src="https://user-images.githubusercontent.com/56600129/150338621-913c8835-fd62-4ebe-81b7-b23cb97ad9c5.png">
Type this regex at the "Match names" field , you get red outline and "save" button disabled.

2. Go to "Path Mapping", add new path. Edit "Match" field - add match: /(one|two). You get red outline and "save" button disabled.
<img width="1238" alt="security policy match or regex" src="https://user-images.githubusercontent.com/56600129/150338683-6242baaa-0993-4eee-98fc-f4886aed9d3a.png">

*Regex expression for case insensitivity (?i)\ isn't allowed also.

**Expected behavior**
We should allow regex with "or" condition

**Desktop (please complete the following information):**

 - Browser chrome
 - Version Curiefense 1.4.0

**Comment by Aviv-Galmidi** [comment]
Can be re-tested, should be fixed now

**Comment by olgasobolevsky** [comment]
Re-tested for regex : (new|path), new[1-9]+, (?i)new, /new$. Behavior as expected.
