### ISSUE TITLE
Test test_non_allowlisted_value_restrict[params-name-ignore_alphanum] fails

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#67]
Version: 11577746dc8c23b1bda4094dfa9000e192f0a649

To reproduce on a minikube deployment:
```
export IP=$(minikube ip); pytest --log-level INFO --base-protected-url http://$IP:30081 --base-conf-url http://$IP:30000/api/v1/ --base-ui-url http://$IP:30080 -k 'test_non_allowlisted_value_restrict[params-name-ignore_alphanum]'
```

Observed error logs for queries associated to this test: none

This request should be accepted: the query parameter value is `invalid`, and the "Ignore Alphanumeric input" checkbox is ticked.

7 variants of this test also fail.

![2020-12-21-164424_991x417_scrot](https://user-images.githubusercontent.com/73547485/102794555-d6f85680-43ab-11eb-8101-723f32092231.png)
![2020-12-21-164411_1035x470_scrot](https://user-images.githubusercontent.com/73547485/102794557-d790ed00-43ab-11eb-9820-2c3ae46bc748.png)

**Comment by tzuryby** [comment]
Is the regex pattern == ```[v]+[a]{1}|?u*e``` ?
this seems to yield "pattern error: ? The preceding token is not quantifiable".

**Comment by xavier-rbz** [comment]
No errors are visible. If this pattern is invalid, that's another issue.

I get the same problem when the matching value is set to "value".

**Comment by tzuryby** [comment]
Fixed.
regex for alpha num was incorrect (missing "+") for multiple cahractares.
