### ISSUE TITLE
Flow control - "Count by" attribute:tag doesn't work

### ISSUE THREAD

**Issue by olgasobolevsky** [curiefense/curiefense#672]
**Describe the bug**
Flow control with "count by" attribute:tag doesn't block on flow violation.

**To Reproduce**
1. Go to Global filter -> create filter with tag:tag1 and condition: header:test:val.
<img width="1419" alt="global filter tag1" src="https://user-images.githubusercontent.com/56600129/150783695-7474390f-d6ab-4386-9b6a-d5fcafef4355.png">

2. Go to Flow control -> create policy with
Count by: attribute: tag
Include:tag1
Action:503
2 sequences.
<img width="1419" alt="fc test by tag" src="https://user-images.githubusercontent.com/56600129/150783742-f75e214d-965e-4514-8234-90d21e6fbfa7.png">

3. Send request for the second sequence with header:test:val to activate action.
4. Tag: tag1 present, request doesn't blocked.

<img width="1419" alt="Screen Shot 2022-01-24 at 14 38 32" src="https://user-images.githubusercontent.com/56600129/150784619-8a4d5335-698a-4249-aba8-fafb77e42345.png">

**Expected behavior**
The request is blocked.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome
 - Version 1.4.0

**Comment by bartavelle** [comment]
You should have this error message in the logs: `Unknown attribute tags`. Counting by tags doesn't make much sense I think. What should the semantics be? For example, all requests are tagged with `all`, so if we run it with "common" tags, they would all match in the same bucket. However, if we match by "all the tags", no two requests will have the same set I think.

**Comment by olgasobolevsky** [comment]
If counting by tags doesn't make sense, why we have that attribute in the list? What the purpose of this attribute option?
(I would suggest counting by specific tag. Like the counting by header/cookie/argument, count by tag:name_of_the_tag.)

**Comment by bartavelle** [comment]
I don't know why it is in the list :) perhaps it makes sense to have it but I do not understand it. Counting by a specific tag might be more useful indeed, but tags are binary, so there would only ever be two categories.

**Comment by olgasobolevsky** [comment]
@ItaiPrajgrod @Aviv-Galmidi What do you think?

**Comment by ItaiPrajgrod** [comment]
@bartavelle the purpose of tags is to create a custom rule to evaluate sessions that match it (using tag rules) and create a flow control sequence with it. In general - we want all our security features to work with tags.

**Comment by bartavelle** [comment]
Sure but I have no idea at all of what this should do!

**Comment by olgasobolevsky** [comment]
@yanivreblaze and @ItaiPrajgrod what do you think?

**Comment by olgasobolevsky** [comment]
@bartavelle As Yaniv explained to me, the match should be by all the tags (all tags together should be the same). In addition, if we have tag in Include, the match should be by all tags + the include tag.

**Comment by bartavelle** [comment]
Got it. This is going to be really flaky though, as tags are altered during flow control and limit checks ...

**Comment by bartavelle** [comment]
PR submitted.
