### ISSUE TITLE
Flow control - "Count by: Query" counts requests without query string

### ISSUE THREAD

**Issue by olgasobolevsky** [curiefense/curiefense#673]
**Describe the bug**
Flow control policy with "Count by: Attribute: Query" initiates action on request without query string.

**To Reproduce**
1. Go to Flow control -> create new policy with:
Count by: Attribute: Query
Action: 503
2 sequences: first with method "POST", second with method "GET"
<img width="1144" alt="FC count by query" src="https://user-images.githubusercontent.com/56600129/150798343-7ea86fa1-0117-43a0-9111-71a105962ab2.png">

2. Send GET request without query string:
curl -vv -H "Host:olga.com" '34.107.23.252:30081/test'

3. The request blocked with: 503.
<img width="1144" alt="log count by query" src="https://user-images.githubusercontent.com/56600129/150798583-ad9ee224-04cb-44c8-b12b-097e4ce1297f.png">

**Expected behavior**
Requests without query string don't get evaluated by the rule

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome
 - Version 1.4.0

**Comment by bartavelle** [comment]
It is considered as the empty query. Requests without query strings should be ignored?

**Comment by olgasobolevsky** [comment]
@ItaiPrajgrod @Aviv-Galmidi What do you think?

**Comment by ItaiPrajgrod** [comment]
@olgasobolevsky , @bartavelle - Yes, this is a bug

**Comment by olgasobolevsky** [comment]
For Rate Limits also. Attribute:Query counts requests without query string.

**Comment by bartavelle** [comment]
Fix pushed in the `merge` branch, let me know if this works.

**Comment by olgasobolevsky** [comment]
@bartavelle This works, thanks.
