### ISSUE TITLE
Flow control - "Action:Tag only" adds tag when the sequence is fulfilled

### ISSUE THREAD

**Issue by olgasobolevsky** [curiefense/curiefense#674]
**Describe the bug**
Flow control - "Action:Tag only" adds tag to the last request in the sequence regardless rule is violated or not.

**To Reproduce**
1. Go to Flow control policies -> create new policy:
Name: FC rule
Time frame: 60
Count by: Attribute: IP Address
Action: Tag only
2 sequence sections:
a) method: GET
Host: olga.com
Path: /test
b) method: GET
Host: olga.com
Path: /test123
Save and publish.
2. Send GET request to olga.com/test
3. Send GET request to olga.com/test123
4. Go to the log, check the tags of the last request: tags: fc-test in the list of tags.

**Expected behavior**
check the tags of the last request: tags: fc-test not in the list of tags.

**Desktop (please complete the following information):**
 - OS: Mac os
 - Browser  chrome
 - Version 1.4.0

** This  behavior is true for each "Action",  not only "tag only" action, - tag of the test is added to the last request regardless rule was violated or not.

**Comment by bartavelle** [comment]
Tag only indeed doesn't make sense, as the request is *always* tagged when reaching the last step. I *think* the reason is that this way you can verify that a request was flow-control checked.

**Comment by olgasobolevsky** [comment]
Same bug with Flow control policy -> Action: Ban; Ban action: Tag only

**Comment by bartavelle** [comment]
You should have the tag added on every action type. Perhaps the option should altered to add another tag instead?

**Comment by olgasobolevsky** [comment]
@ItaiPrajgrod @Aviv-Galmidi What do you think?

**Comment by ItaiPrajgrod** [comment]
@olgasobolevsky , @bartavelle - In this case, each request that violates the configured flow control sequence should be tagged.

**Comment by bartavelle** [comment]
But it currently tags every request that goes to the last stage, regardless of the action type. That is why "tag only" currently makes no sense.

**Comment by bartavelle** [comment]
So in that case, do we agree that "tag only" is a noop, as tags are always emitted, regardless of action type?

**Comment by olgasobolevsky** [comment]
"In this case, each request that **violates** the configured flow control sequence should be tagged.
""tag only" is our option of "report only" - it allows the user to configure flow control analysis but without mitigation. The **violated sessions** will be presented in the reports (and dashboards) but will not be blocked."
As I understand, only **violation** of the rule should be tagged. As it implemented now, we tag on correct flow also.

**Comment by bartavelle** [comment]
Just to double check : tagging should not happen when the correct flow is triggered. Sorry, I am being extra painful because I was asked to implement it that way here:

https://github.com/curiefense/curiefense/commit/a78458a2a951e265a41e8d790c7ae0dbd986420d

I don't have a design document or an issue to reference for this change, but as far as I remember the rationale was that you would know if it was blocked or not based on other logged attributes, but you wanted to know the request was well flow-checked.

**Comment by ItaiPrajgrod** [comment]
Adding @Yaniv Yagolnitzer ***@***.***>, that defined the feature, to
the discussion.
WDYT?

**Comment by yanivreblaze** [comment]
I agree with @ItaiPrajgrod  on that scenario 2 is not needed , but for reference 
where a request had passed through flow control successfully  we probably would need additional tag 
that is different than the action TAG.
 
Scenario 1 : 
`Request => Flow => Violation => TAG`

Scenario 2 :
`Request => Flow => No Violation => TAG`

**Comment by olgasobolevsky** [comment]
By design, not a bug.
