### ISSUE TITLE
Flow control - "Action: Ban; Ban action: Challenge" activates block 503 action

### ISSUE THREAD

**Issue by olgasobolevsky** [curiefense/curiefense#675]
**Describe the bug**
When Flow control policy has "Action: Ban; Ban action: Challenge" and the rule is violated, the action is block with status code 503 (not the challenge).

**To Reproduce**
1. Go to Flow Control -> create policy with:
2 sequence sections.
Action: Ban; 180 sec;
Ban action: challenge
Save and publish.
2. Send request to the second sequence section to activate the action of the rule.
3. Response: 503 Service Unavailable
(Same response for curl and for browser.)
4. Check the log: Response code 503, no challenge

**Expected behavior**
Challenge execution on rule violation.

**Desktop (please complete the following information):**
 - OS: Mac os
 - Browser chrome
 - Version 1.4.0

**Comment by bartavelle** [comment]
Should only the last action of the sequence be banned?

**Comment by bartavelle** [comment]
See #629 which is also blocked because it is unclear what ban means in that context.

**Comment by olgasobolevsky** [comment]
I think, the action should make affect only on the last request in the sequence flow. 
@ItaiPrajgrod @Aviv-Galmidi What do you think?

**Comment by bartavelle** [comment]
But on every step of the flow control, or only for the last step?

**Comment by ItaiPrajgrod** [comment]
Only from the point it violates the flow control sequence (it can be last in the sequence or before).

**Comment by bartavelle** [comment]
Please check the linked PR to see if it solves the issue!
