### ISSUE TITLE
Global filters - Cookie/Argument/Header entry with match key:!value, triggers action on !(key:value) match 

### ISSUE THREAD

**Issue by olgasobolevsky** [curiefense/curiefense#682]
**Describe the bug**
Create filter with entry Cookie/Argument/Header with defined key1 and not (!) condition on the value1. Send requests with Cookie/Argument/Header keys and values. All requests will trigger action except request with exact key1 and value1 match.

**To Reproduce**
1. Go to Global filters -> create new filter with:
tag:tag1
Section: Cookie: foo: !boo
action: tag only
<img width="1440" alt="gf cokie with not" src="https://user-images.githubusercontent.com/56600129/151358542-e460c924-e065-4a56-b1fc-ba966c63e51c.png">

Save and publish.
2. Send request with cookie: test:olga
3. Send request with cookie: test:boo
4. See the log: requests have "tag1" tag in tags.
<img width="1440" alt="gf cookie log" src="https://user-images.githubusercontent.com/56600129/151359045-7ca19537-3f75-45bf-ae48-67b055593e49.png">

**Expected behavior**
This requests shouldn't have the "tag1" tag, they shouldn't trigger action of the filter

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Browser chrome
 - Version 1.4.0

**Comment by bartavelle** [comment]
What should be done for the other fields that are not key/value, but that might lack a value (such as geoip stuff)

**Comment by olgasobolevsky** [comment]
@yanivreblaze and @ItaiPrajgrod what do you think?

**Comment by bartavelle** [comment]
I guess this should be good now?
