### ISSUE TITLE
Rate limits - Action Ban:503 , bans for more time than defined in rule

### ISSUE THREAD

**Issue by olgasobolevsky** [curiefense/curiefense#686]
**Describe the bug**
Rate limit with action Ban:503, bans for more time than defined in rule.

**To Reproduce**
1. Go to Rate limits -> create new rate limit with:
Time frame: 20
Count by: IP
limit:3
Action: Ban: for 120 sec
Ban action: 503 
2. Send 4 request to activate the ban.
Note the time ban starts (13:21:29).
Send request after 120+ sec (13:23:50) - response 503
Send request after 180+ sec (13:24:49) - response 503

**Expected behavior**
Send request after 120+ sec (13:23:50) - response 200
Send request after 180+ sec (13:24:49) - response 200

*Same bug for all Ban actions: Challenge, Tag only, Response, Redirect.

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser chrome

**Comment by bartavelle** [comment]
I can't reproduce :(

Are there no requests in-between (for example browsers automatically retrying)? Might there be other limits active at the same time?

If everything seems fine, can you paste the proxy logs (the docker-compose logs) that correspond to all requests?  Thanks in advance!

**Comment by bartavelle** [comment]
@ItaiPrajgrod @Aviv-Galmidi Should the implementation or the documentation be altered?

**Comment by olgasobolevsky** [comment]
@yanivreblaze and @ItaiPrajgrod what do you think?

**Comment by olgasobolevsky** [comment]
@Aviv-Galmidi

**Comment by Aviv-Galmidi** [comment]
I'm not sure which one is correct between the current implementation and documentation
@tzuryby or @yanivreblaze Do you remember why when setting a ban action in Curiefense, the ban timer resets if new requests are being sent during the ban duration? Should this be the case or is the ban duration absolute?

**Comment by bartavelle** [comment]
It's been decided that the current behavior was a bug. c1c5a47b9c952370c914592ca84fc762f0a11804 should fix it.
