### ISSUE TITLE
Test test_ratelimit_countby_tag fails

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#69]
Version: d2819bec4ec8ac30066dac2a283a8994e207c019

To reproduce on a minikube deployment:
```
export IP=$(minikube ip); pytest --log-level INFO --base-protected-url http://$IP:30081 --base-conf-url http://$IP:30000/api/v1/ --base-ui-url http://$IP:30080 -k 'test_ratelimit_countby_tag'
```

Observed error logs for queries associated to this test: none

This test works as follows:
* Define a rate limit rule, where "count by" is set to "tag", with ttl=10 and threshold=5.
* Send 5 queries coming from a first source IP, and 5 queries coming from a second source IP. All are allowed, which is normal. All queries have the same tags, except for the `ip:` tag.
* Send a 6th request coming from each of these source IPs, within the TTL. These requests are not blocked, despite being the 6th request (for each IP) with the same set of tags.

![2020-12-21-184355_1018x273_scrot](https://user-images.githubusercontent.com/73547485/102806277-e0d68580-43bc-11eb-98ca-860888e23db8.png)
![2020-12-21-184341_998x329_scrot](https://user-images.githubusercontent.com/73547485/102806278-e16f1c00-43bc-11eb-8777-c9f25725b8e2.png)

Expected result: the 6th request for each source IP should have been blocked.

**Comment by tzuryby** [comment]
the attribute is empty in the UI Screenshot.
ther should be a name specified.

**Comment by xavier-rbz** [comment]
Test [fixed](https://github.com/curiefense/curiefense/commit/1b800eb3bd994d8dc72e56c86c29644ccc3bb05e#diff-9fbd13d206d66f96905e58a56e4d50cb12715ce47fa9037990333ddaf36744adL333): using "tags" instead of "tag", as the UI would have generated it. Now the config displays properly.

With this change, we get error logs from curieproxy:
```
[Envoy (Epoch 0)] [2020-12-22 13:49:06.686][33][error][lua] [external/envoy/source/extensions/filters/http/lua/lua_filter.cc:600] script log: ./lua/limit.lua:141: attempt to concatenate local 'entry' (a table value)
```

Is "tags" really the expected value? All other attributes are singular (ip, uri, path...)

**Comment by tzuryby** [comment]
this is not a real bug since usnig tag as a key for rate limiting make no sense.
I asked @Aviv-Galmidi  to remove it from the UI along with attribute:authority

**Comment by Lastpixl** [comment]
Test removed in https://github.com/curiefense/curiefense/commit/41b9a9e1dca6d7919f2600e87162042372522e3e
