### ISSUE TITLE
Content filter rules - error at curieproxy log when new rule created

### ISSUE THREAD

**Issue by olgasobolevsky** [curiefense/curiefense#698]
**Describe the bug**
When we create new custom content filter rule, we don't add properties like: severity, certainty, category, subcategory and msg.
Every Curie defined rules have those properties. 
When we have custom rules, on rules evaluation, curieproxy shows error: missing field `msg`.

**To Reproduce**
1. Go to Content filter rules -> add new rule:
Name: New Content Filter Rule
Match: test
Save and Publish.
<img width="1118" alt="new cf rule" src="https://user-images.githubusercontent.com/56600129/152327663-a6fa4ad9-34df-4685-8b72-f37e8ce1077f.png">
<img width="1375" alt="new content filter rule api" src="https://user-images.githubusercontent.com/56600129/152327715-ba8cdd12-d32b-41e1-bb41-51bdc8559644.png">

2. Send request.
Curieproxy log shows error:  missing field `msg`.
<img width="1000" alt="new content filter log error" src="https://user-images.githubusercontent.com/56600129/152327756-5b29d555-a2c2-4aa8-92ad-8ffcd7efcec2.png">

**Expected behavior**
No errors in the log

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Comment by olgasobolevsky** [comment]
On nginx deployment:
Create new Content filter rule - errors at proxy log: missing field `msg`; when resolving the action entry.
<img width="1262" alt="nginx log create new waf rule" src="https://user-images.githubusercontent.com/56600129/156912086-be5260d3-a368-49d5-b6e9-ace7fb2d8d30.png">

**Comment by bartavelle** [comment]
I will not try to fix it for now, as there is a large change in the works that completely change the format of these rules.
