### ISSUE TITLE
Content filter profiles - Match value with regex not(!) doesn't work

### ISSUE THREAD

**Issue by olgasobolevsky** [curiefense/curiefense#707]
**Describe the bug**
When match value regex defined with "not" (!id), every value is mismatch.

**To Reproduce**
1. Go to Content filter profiles -> add parameter:
Cookie: Key:test, Match value: !id, Restrict: checked.
Save and publish.
<img width="1440" alt="cf profile regex not" src="https://user-images.githubusercontent.com/56600129/152682228-5347f755-4249-4fec-b210-41ab2955141a.png">

2. Send request with cookie test:123.
3.  The request is blocked with 403.
![regex not kibana log](https://user-images.githubusercontent.com/56600129/152682177-19151bbd-ee06-4451-b569-0e9c632de40c.png)

**Expected behavior**
Request won't be blocked. Only requests with cookie: test=id will be blocked.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Comment by bartavelle** [comment]
Merged in `merge` branch.

**Comment by yanushg** [comment]
@bartavelle was it fixed for headers and args as well or just this scenario?

**Comment by yanushg** [comment]
@bartavelle Now we do not block anything 
Added cookie to the default content filter and marked "restrict" 
Key: test value:!test 
Not blocking request with --cookie test=test

**Comment by bartavelle** [comment]
Did you uncheck "ignore alphanumeric input" ?
