### ISSUE TITLE
Test test_allow_bot_all fails

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#73]
Version: e46a52ae9ff03e9bd0449ae8f948d033cc061af8

Observed error logs for queries associated to this test:
```
[Envoy (Epoch 0)] [2021-01-07 18:48:22.256][30][error][lua] [external/envoy/source/extensions/filters/http/lua/lua_filter.cc:600] script log: ./lua/waf.lua:258: Bad type of 'data': number
```

**Comment by tzuryby** [comment]
this line suggests regex error in WAF rules.
have my recent changed integrated ?

https://github.com/curiefense/curiefense/blob/e46a52ae9ff03e9bd0449ae8f948d033cc061af8/curiefense/curieproxy/lua/waf.lua#L258

**Comment by jdorfman** [comment]
@flaper87 can we move this issue to a new milestone so we can close out `1.3.0`?

**Comment by flaper87** [comment]
This test seems to be enabled now so I think this issue can be closed. @xavier-rbz am I missing something?

**Comment by xavier-rbz** [comment]
Indeed, it is now enabled & passing. Thanks for the heads-up!
