### ISSUE TITLE
Tags in content filter

### ISSUE THREAD

**Issue by bartavelle** [curiefense/curiefense#757]
This issue describes a evolution of the content filter design. In particular, it adds support for tags in the content filter system, and modifies the content filter rules group system.

# Configuration format changes

## `contentfilter-groups.json`

This file contains a list of group definitions, which are objects where the only required fields are:

 * `signatures`: a list of tags representing the corresponding `id` field of the content filter signatures, e.g. `cf-rule-100023` for signature (rule) id 100023;
 * `tags`: a list of strings

## `contentfilter-rules.json`

A new field appears in the rule object: `tags`, a list of string.

## `contentfilter-profile.json`

Three new fields appear in a profile definition: `active`, `report` and `ignore`, all of them list of strings.

# Expected behavior

The content filter phase works as follows:

 1. current request flags are checked against the list of `ignore` tags of the given profile. If there is an intersection, further processing is skipped. This feature is intended to be used for whitelisting some requests (for example if they are from a trusted source), avoiding the cost associated to content filtering ;
 2. for each section (path, headers, cookies, args), the following checks are performed, in order:
    * maximum amount of values is checked (including decoded content), if exceeded, the request is blocked (see below) ;
    * for each parameter:
       * parameter length is checked (excluding decoded content), if exceeded, the request in blocked (see below) ;
       * if the *ignore alphanum* parameter is checked, and the value is alphanumeric, this parameter will not undergo further inspection ;
       * if the parameter name matches an "exact match" rule, it is checked (see below) ;
       * if it did not match an "exact match" rule, then it is checked for each "regex match" rule that matches its name.
 3. injection checks are performed, possibly updating the current request tags ;
 4. signature checks are performed, possibly updating the current request tags ;
 5. if there is an intersection between the current request **specific** (like `cf-rule-id-XXX`) tags and the content of the profile filter profile `active` tags, the request is blocked ;
 6. if there is an intersection between the current request **specific** (like `cf-rule-id-XXX`) tags and the content of the profile filter profile `report` tags, the request is not blocked ;
 7. if there is an intersection between the current request tags and the content of the profile filter profile `active` tags, the request is blocked ;
 8. if there is an intersection between the current request tags and the content of the profile filter profile `report` tags, the request is not blocked.

Of course, the request will only be blocked if the content filter is active in the selected security policy.

### Parameter matching

Parameter matching works in the following way:

  1. if a *match* regexp was set, the value is compared. If it matches, the process ends here ;
  2. if the `restrict` parameter was set, the request is blocked (see below) ;
  3. if the `exclusions` field intersects with the current request tags, the process ends here. This is also for whitelisting ;
  8. the parameter is added to the list of verified parameters

### Injection checks

For each parameter of each section (that have not been excluded previously), the following is performed:

 * if the exclusion list of the checked parameter or the content filter profile contains one of the libinjection tags for a particular subcategory, no injection checks are performed for this subcategory. If checks are performed and a match is found, the subcategory tags are set. Those tags are:
 * if the `sqli` check, tags are `cf-rule-id:libinjection-sqli`, `cf-rule-category:libinjection`, `cf-rule-subcategory:libinjection-sqli`, `cf-rule-risk:libinjection`,
 * if the `xss` check, tags are `cf-rule-id:libinjection-xss`, `cf-rule-category:libinjection`, `cf-rule-subcategory:libinjection-xss`, `cf-rule-risk:libinjection`.
 
### Signature checks

For each parameter of each section (that have not been excluded previously), the following is performed (in practice, this is not what happens, for performance reason they are all scanned together, and, in case of a match, the following process happens, but semantically it should be the same), all rules that have tags matched by the `active` or `report` field of the content filter profile are checked.

For every rule that matched, the following tags are added to the current query tags, unless it is in the `ignore` list of the given content filter profile, or in the ignore list of the given parameter:

 * all tags from the `tags` field of the rule ;
 * all tags from the `tags` field of the rule groups this rule is a member of ;
 * `cf-rule-id-XXX`
 * `cf-rule-risk-Y`
 * `cf-rule-category-ZZZ`
 * `cf-rule-subcategory-AAA`
 
# Examples

## Single match, several columns

What happens if a **SINGLE RULE** is matched between several columns?

In the following table, `specific` == `cf-rule-id-XXX`

| In ignore | In active | In report | Result |
|-----------|-----------|-----------|--------|
| no match  | no match  | no match  | pass   |
| *specific*  | anything  | anything  | pass   |
| category  | anything  | anything  | pass   |
| no match  | *specific*  | anything  | block  |
| no match  | category  | *specific*  | report |
| no match  | category  | no match  | block  |

Note: ignore always wins, so it is dangerous to put anything but specific rule ids in it.

# Two matches, several columns

If two rules matches, the following happens:

 * if one of the rules is ignored, see the previous section result, or else
 * if rule1 or rule2 has a specific entry in the `active` column, block, or else
 * if rule1 or rule2 has a specific entry in the `report` column, report, or else
 * if rule1 or rule2 has a category entry in the `active` column, block, or else
 * if rule1 or rule2 has a category entry in the `report` column, report, or else
 * pass

**Comment by tzuryby** [comment]
> Should "ignored" parameters also ignore length checks / restrict settings ?
No. those are two separated settings which should not mixed.

> Is the priority between active / report / ignore correct ?
if a sig is matched under active, then active is taking place, regardless of the fact _it is also matching with other tags under ignore or report_ 

> Is it OK to exit early from the content filter checks if an ignore tag is checked ?
ignroe tags means, if there is a match against a signature that has (or its group) matching tag. not stop checking other sigs
