### ISSUE TITLE
Generate CODEOWNERS file

### ISSUE THREAD

**Issue by jdorfman** [curiefense/curiefense#83]
**Is your feature request related to a problem? Please describe.**

For the CNCF onboarding, there is a **required task** asking us to provide:

> Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list.

**Describe the solution you'd like**

We need a way to generate `CODEOWNERS`. That looks like This is what it should look like: https://github.com/coredns/coredns/blob/master/CODEOWNERS

**Additional context**

Some links that are relevant to this issue

* https://github.blog/2017-07-06-introducing-code-owners/
* https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
* https://docs.gitlab.com/ee/user/project/code_owners.html

**Comment by flaper87** [comment]
> We need a way to generate CODEOWNERS. That looks like This is what it should look like: https://github.com/coredns/coredns/blob/master/CODEOWNERS

This is, commonly, generated manually. We can create one that is a bit generic for now and then be more specific as the project evolves.
