### ISSUE TITLE
Enable DCO

### ISSUE THREAD

**Issue by caniszczyk** [curiefense/curiefense#87]
CNCF IP Policy requires DCO: https://github.com/apps/dco

**Comment by caniszczyk** [comment]
@jdorfman I have enabled it here: https://github.com/organizations/curiefense/settings/installations/14390740

Please ensure that commits + pull requests moving forward are signed off with DCO and the bot checks :)
https://probot.github.io/apps/dco/

**Comment by jdorfman** [comment]
will do @caniszczyk thanks!

**Comment by jdorfman** [comment]
We are good to go @caniszczyk thanks again for your help.

https://github.com/curiefense/curiefense/pull/91/checks?check_run_id=1798351264
