### ISSUE TITLE
Rewriting the Lua code into Rust

### ISSUE THREAD

**Issue by bartavelle** [curiefense/curiefense#90]
This thread is for discussing the current work on rewriting the Lua code into Rust.

# General strategy

## Using the WASM backend

This seems like an excellent idea, given that envoy supports WASM filters, and it is really easy to write WASM module with Rust.
However, this is far too constrained, as the WASM sandbox does not allow:

 * reading files on the disk (configuration can't be loaded)
 * connecting on other hosts using TCP (redis servers can't be contacted)

## Writing a native extension to envoy

This would be the most convenient, but would require recompiling envoy.

## Writing a native library, called from Lua

This is where the current development effort is being poured. There are however several downsides:

 * According to [https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#overview](the envoy docs), the Lua is hacked in some way so that IO is made asynchronously. File and Redis accesses from the Rust library will probably stall the envoy thread, hurting performance
 * It is not that straightforward to interface with Lua. I am currently using the `mlua` crate which kind of work. Except that it is not possible to throw Lua exceptions (turns into a segmentation fault)
 * The cost of serializing/deserializing between envoy <-> lua <-> rust might be significant (is most probably not)

**Comment by bartavelle** [comment]
Work is happening here: https://github.com/curiefense/curiefense/tree/wasm_test

It requires a slight modification to session.lua:

```lua
local native        = require "curiedefense"

[...]

function inspect(handle)

    local headerm = {}
    for k, v in pairs(handle:headers()) do
        headerm[k] = v
    end

    native.inspect(headerm)

[...]
```

**Comment by bartavelle** [comment]
I have questions about behavior that I found surprising, and would like a confirmation they are to be implemented in Rust as they are in Lua:

 * regex matches on hosts/urls/headers/etc are not anchored. This would be, to me, the expected behavior. The problem is that this sample (from *Curiefense Proxy High Level Flow and Algorithms*):
 
```json
      {
        "name": "Login V3",
        "match": "/api/v3/login",
        "acl_profile": "f6c35fa9fa15",
        "acl_active": true,
        "waf_profile": "__default__",
        "waf_active": true,
        "limit_ids": []
      }
```
Lacks a `^` in the regex, allowing matches such as `http://foo/bar/api/v3/loginator`. Is that the expected behavior, or is an implicit `^` expected? Same question for headers.

 * If, in an ACL profile, the **same** tag is present in `deny` and `deny_bot`, human users will **not** be denied.

**Comment by bartavelle** [comment]
(it is not important if the same tag is present, what matters is that the human would match tags in both `deny` and `deny_bot`)

**Comment by tzuryby** [comment]
it is by design.
user can set whatever regex they pleased, starting with ^ or not.
for example, /images/ would match any path with images and a specific policy for it regardless of its prefix or suffix.

**Comment by flaper87** [comment]
@bartavelle any updates on this? When do you think there will be a PR ready? This is quite exciting :D

**Comment by bartavelle** [comment]
Yes, I am working with @tzuryby on this, on the `tzuryrust` branch. Last week I wrote a test function that can compare the result of the Rust and Lua code. Currently it only does request tagging + acl checks, but hopefully it will allow us to iterate quickly.
