### ISSUE TITLE
Possible bug (vulnerability?) in utils.lua:map_ip

### ISSUE THREAD

**Issue by bartavelle** [curiefense/curiefense#92]
**Describe the bug**
The ip address can be set to `nil` depending on the content of `xff_trusted_hops` and `x-forwarded-for`.

**To Reproduce**

If the value in `xff_trusted_hops` is equal to the amount of ips in `x-forwarded-for`, the client IP is resolved as `nil`.
I am not sure if that is a practical problem (I do not know how `xff_trusted_hops` is set).

I reproduced this code: https://github.com/curiefense/curiefense/blob/1a4147d75f31275ab03408ada5ae6364b6c201a7/curiefense/curieproxy/lua/utils.lua#L120-L132

Into the standalone Lua:
```lua
local client_addr = "1.1.1.1"
local addrs = {"1.2.3.4", "5.6.7.8", "9.10.11.12"}
local hops = 3

if #addrs == 1 then
    client_addr = addrs[1]
elseif #addrs < hops then
    client_addr = addrs[#addrs]
else
    client_addr = addrs[#addrs-hops]
end

print(client_addr)
```

Which outputs `nil`.

**Expected behavior**

I do not really know :)

**Additional context**

As far as I know this might be something that ever happens, but there is code to cope for a mismatch between the headers and metadata.

**Comment by tzuryby** [comment]
Good spotting.

The source of this issue was in the fact, Google LB adding its own public IP and private IP into the XFF (perhaps given its internal routing).


the right one is as follows:


```
function detectip(xff, hops) 
    local len_xff = #xff
    print (len_xff)
    if hops < len_xff then
        return xff[len_xff-(hops-1)]
    else
        return xff[1]
    end
end

xff = {"1.2.3.4", "2.3.4.5", "3.4.5.6", "4.5.6.7"}

trusted_hops = 1
print (detectip(xff, trusted_hops))
trusted_hops = 2
print (detectip(xff, trusted_hops))
trusted_hops = 3
print (detectip(xff, trusted_hops))
trusted_hops = 4
print (detectip(xff, trusted_hops))
trusted_hops = 5
print (detectip(xff, trusted_hops))
```

meaning, we are picking the right one from the right end of the list.
I will update the Lua code.
CPP Should follow these as well.
