### ISSUE TITLE
Version: 1.3.0 Release Notes

### ISSUE THREAD

**Issue by jdorfman** [curiefense/curiefense#94]
This issue is for me however I will need help from @tzuryby and others since I joined the project. According to our [ROADMAP](https://github.com/curiefense/curiefense/blob/master/ROADMAP.md) our next version number will be `v1.3.0`.

Searches that will give us a good overview of what has happened since `v1.0.0`.  :

- [x] `git log --pretty=format:"%t %ar %an %s" --graph`
- [x] `git log --grep 'add'`
- [x] `git log --grep 'update'`
- [x] `git log --grep 'improved'`
- [x] `git log --grep 'remove'`
- [x] `git log --grep 'fix'`
- [x] `git log --grep 'enhance'`

The Release Notes (Changelog) will be in the same format that [Envoy distributes theirs](https://www.envoyproxy.io/docs/envoy/v1.17.0/version_history/current). They truly set the bar when it comes to Changelogs.

[archive](https://gist.github.com/jdorfman/e25eed0a3ae1104b83c511e9b8a7cc23)

**Comment by jdorfman** [comment]
**Things that caught my eye so far**

* `a641524 3 months ago phil Added curietasker draft`
* `78a533e 3 months ago phil Added 'update_and_publish' task`
* `ea2a604 3 months ago phil Add ability to use "*" in place of config and branch lists in task db`
* `e68c92a 3 months ago phil Bootstrap unit tests for curietasker`
* `ddb2f89 3 months ago Xavier curiesync: add option to make synchronization quiet, enable it in helm deployments`
* `59fc071 2 months ago phil Added AVL rebalancing`
* `34befe0 2 months ago phil Added tests to avltree`
* `9ac185f 2 months ago phil Added height computation`
* `a9d7e68 9 weeks ago Aviv-Galmidi add-entries-relations-support`
* `c726409 2 months ago phil Added in-place entry edition in curieconf (server, client, CLI)`
* `9d4d6d8 8 weeks ago phil Added geoipdb bindings to iptools`
* `1b81365 8 weeks ago tby new iptools with maxmind`
* `125c73a 8 weeks ago tby Update Envoy to v1.16.2`
* `217b7f9 8 weeks ago tby better hscan integration -- loading from json`
* `3ef0079 8 weeks ago Xavier curielogger: add sql latency metrics`
* `53534aa 8 weeks ago Xavier grafana: add curiefense-system dashboard`
* `69e4c28 7 weeks ago Aviv-Galmidi enhance-rate-limit-editor`
* `4445141 6 weeks ago Xavier e2e: improve bot_deny testing`
* `c99db01 4 weeks ago Aviv-Galmidi json-editor-tree`
* `58d51c4 4 weeks ago Aviv-Galmidi tags-manager`
* `e0d4077 6 weeks ago Xavier docker-compose: add ELK containers`
* `574d183 3 weeks ago Xavier helm: add elasticsearch support`
* `b2787fa 3 weeks ago phil Big curielogger rewrite. New architecture. Preparation for multiple backends`
* `b429503 3 weeks ago phil Added logstash support to curielogger`
* `fb37389 3 weeks ago phil Added alpha fluentd support to curielogger`
* `c9290db 9 days ago Flavio Percoco Add city lookup capabilities to iptools`

**Comment by jdorfman** [comment]
`git log --grep 'add'`

* `Add CodeQL Security Scanning`
* `Add continent data and more country data`
* `Add geolocation for requests when data is present`

**Comment by jdorfman** [comment]
* e2e: add rate limit query&tag&authority scope tests
* e2e: add rate limit asn & method scope tests
* e2e: add rate limit company scope tests
* e2e: add rate limit country scope tests
* e2e: add test for ratelimit scope by ip
* e2e: add tagrule test with AND
* e2e: add TagRules test for ASN, country, ipv4, ipv6. Use new rule format.
* add minikube latency testing script
* e2e: add logs smoke tests
* [curieproxy] add missing lua dependency

**Comment by jdorfman** [comment]
* [docker-compose] ELASTICSEARCH_URL added to curielogger entry in compose yaml
* [curieproxy] tests branch configuration added
* [curieconf] tests branch configuration added
* [ui] added links to side menu
* [curieproxy] benchmark and tests added
* [curieproxy] added debug message for Rust Sig
* [curieproxy] rust calls with debug -- :add instead of .add
* [curieproxy] debug messages added
* [curietasker] log info added for remote debugging 
* [curietasker] adding jsonschema to setup.y install_requires
* [curieproxy] debug added to tagging matching points

**Comment by jdorfman** [comment]
### Update

* [curielogger] Update deployment configs/files
* [tests] Update .github/workflows/codeql-analysis.yml
* [e2e] update smoke test patterns & script
* [helm] Update logstash pipeline configuration
* [e2e, tests] update ratelimit for test action-ban-503
* [e2e] update curiefense-fluentd-patterns.txt
* [curielogger] Update cflog format and add pg back
* [curielogger] Update curielogger for new format
* [docker-compose] update env variables for curielogger
* [helm] update chart following changes in curielogger

**Comment by jdorfman** [comment]
### Improved

* [ui] Improved performance for EntriesRelationList prop validator
* [iptools] improved Node.dump()

**Comment by jdorfman** [comment]
### Remove

* [ui] Flow Control - Removed the regex symbol next to Method, Host, and Path
* [curielogger] removed addition of hardcoded path to logstash url
* [curieproxy] removed reference to bt 
* [curieproxy] schema removed, waf sig corrected
* [curieproxy] Removed old unused schema files
*

**Comment by jdorfman** [comment]
### Fix

* [e2e, helm] fix log deletion in checklogs-helm.sh

**Comment by jdorfman** [comment]
### Enhance

* Enhance api to allow requesting specific properties of documents

**Comment by jdorfman** [comment]
@flaper87 want me to turn this into 1 markdown file so you and @tzuryby can easily review it?

**Comment by flaper87** [comment]
> @flaper87 want me to turn this into 1 markdown file so you and @tzuryby can easily review it?

Yes, please! I think that would really help going through this content. There's quite some cleaning to do here. :sweat_smile:

**Comment by jdorfman** [comment]
@flaper87 Check https://github.com/curiefense/curiefense-gitbook/blob/v1.2.4/reference/release-notes.md

**Comment by flaper87** [comment]
I edited the list manually following these criteria:

* Remove lines that are not user-facing
* Remove lines without descriptions

```
---
description: 'aka Version History, Changelog'
---

# Release Notes

### Version 1.X.X

#### Enhanced

* \[curieconf\] Enhance API to allow requesting specific properties of documents

#### Added

* \[curieproxy\] Add continent data and more country data
* \[curieproxy\] Add geolocation for requests when data is present
* \[curielogger\] Add config file structure
* \[curieproxy\] Add continent data and more country data
* \[ui\] Added 3 categories to tags \(legitimate, malicious, neutral\)
* \[curieconf, ui\] Added mask boolean field to WAF policy Cookie/Header/Argument
* \[ui\] Added is-single-input-column prop to ResponseAction component
* \[ui\] Added more tests to DocumentSearch component \(98%+ Coverage\)
* \[ui\] Added routing to document editor page per the following schema: /config/branch/doc\_type/doc\_id
* \[ui\] Added search page for documents
* \[ui\] Added units suffix \(seconds\) to TTL in RateLimitsEditor.vue
* \[ui\] Added units suffix \(seconds\) to TTL in FlowControlEditor.vue
* \[ui\] Added ace json editor to DB editor screen
* \[ui\] Added default textarea json editor when failing to load ace json editor
* \[ui\] Added indicator for missing data in DocumentEditor.vue
* \[ui\] Added indicator for loading data in DocumentEditor.vue
* \[ui\] Added indicator for missing data in DBEditor.vue
* \[ui\] Added indicator for loading data in DBEditor.vue
* \[ui\] Added scrollbar to Burma’s dropdown menu item with max height of 12rem
* \[confserver\] Added an example flow control document to bootstrap data
* \[confserver\] Added basic tags to bootstrap data
* \[confserver\] Add geolite2 city
* \[curielogger\] elasticsearch index: add timestamp field
* \[images\] add fluentd image
* \[helm\] add fluentd support
* \[helm\] add elasticsearch support
* \[docker-compose\] add ELK containers
* \[helm\] deployments: add support for google storage buckets
* \[helm\] deployment: add variables to disable parts of the chart
* \[curieproxy\] add missing lua dependency
* \[curielogger\] Added alpha fluentd support
* \[curielogger\] Added logstash support
* \[curielogger\] Added elasticsearch dumb client
* \[curieproxy\] Added envoy-1.16.2 binary with symbols for lua
* \[curieconf\] Added in-place entry edition in curieconf \(server, client, CLI\)
* \[curietasker\] Added 'update\_and\_publish' task
* \[curietasker\] Added 'publish' task
* \[docker-compose\] ELASTICSEARCH\_URL added to curielogger entry in compose yaml
* \[curieproxy\] tests branch configuration added
* \[curieconf\] tests branch configuration added
* \[ui\] added links to side menu
* \[curieproxy\] benchmark and tests added
* \[curieproxy\] added debug message for Rust Sig
* \[curieproxy\] rust calls with debug -- :add instead of .add
* \[curieproxy\] debug messages added
* \[curietasker\] log info added for remote debugging
* \[curietasker\] adding jsonschema to setup.y install\_requires
* \[curieproxy\] debug added to tagging matching points

#### Updated

* \[curielogger\] Update deployment configs/files
* \[helm\] Update logstash pipeline configuration
* \[curielogger\] Update cflog format and add pg back
* \[curielogger\] Update curielogger for new format
* \[docker-compose\] update env variables for curielogger
* \[helm\] update chart following changes in curielogger
* \[bootstrap-script\] updated version to 1.2.10
* \[bootstrap-script\] Updated axios version to avoid security vulnerability
* \[confserver\] update bootstrap waf signatures
* \[confserver\]: update profiling lists for confdb bootstrap bundle

#### Improved

* \[ui\] Improved performance for EntriesRelationList prop validator
* \[ui\] Replaced all download functions with a new downloadFile function in Utils
* \[curieconf\] Enhance api to allow requesting specific properties of documents
* \[ui\] Use the new enhanced api to drastically improve loading time of “Search Document” page
* \[ui\] Added scrollbar to Burma’s dropdown menu item with max height of 12rem
* \[ui\] Fixed download button in AccessLog component
* \[ui\] Changed colors of JSON Editor menu and mode selector to greyscale
* \[ui\] Hiding "Clear all sections" button in tagrules when source of list is not "self-managed"
* \[ui\] Fix indentation of WAF policy editor and WAF signature viewer content
* \[ui\] Fix bug preventing docs from being downloaded
* \[ui\] Fix name of all download buttons \(removed unneeded 'x'\)
* \[ui\] Now using new document defaults for missing props of documents

#### Removed

* \[ui\] Flow Control - Removed the regex symbol next to Method, Host, and Path
* \[curielogger\] removed addition of hardcoded path to logstash url
* \[curieproxy\] removed reference to bt
* \[curieproxy\] schema removed, waf sig corrected
* \[curieproxy\] Removed old unused schema files
* \[confserver\] Removed unneeded params from bootstrap flow control action prop
* \[ui\] Removed unneeded module from dependencies
* \[ui\] Removed inline styling, !important, tag
* \[ui\] Added main.scss containing general classes
* \[ui\] Removed unneeded whitespace
* \[ui\] Improvements to the ui - general alignment of components throughout the system
* \[ui\] Removed deprecated html tag
* \[curieproxy\] removed logs
* \[curieproxy\] hscan.lus removed
* \[curieproxy\] globals.WAF removed
* \[ui\] Removed unnecessary card wrapper
* \[ui\] Removed conversion of old entries + relation data structure to the new structure, should be received from server in correct new structure
* \[curietasker\] return false removed
* \[curietasker\] removed some more debug prints
* \[curieconf\] remove references to now removed mongobackend package
* \[curieconf\] Removed outdated mongo backend
* \[curieconf\] Removed any loose API calls
* \[curieconf\] Removed duplicated API call in AccessLog.vue

#### Fixed

* \[curielogger\] Fix indexpatter for non data stream environments
* \[deploy, docker-compose\] fix use of fluentd
* \[deploy\] deploy-dev.sh: fix log check step
* \[currielogger\] elasticsearch mapping: fix types for arrays
* \[curielogger\] omit keys in upstream when there is not upstream \(fixes ES\)
* \[ui\] fix jest global window
* \[curielogger\] fix json names
* \[curielogger, helm\] elasticsearch: deployment fixes
* \[ui\] Fixed Bug - When creating multiple documents in a row throws an error
* \[curielogger\] Fixed missing fields in request attribute structure
* \[curieproxy\] waf exclude restrict bug fixed
* \[curieproxy\] acl bug fixed
* \[curieproxy\] more debug messages -- bad data type number error fixed
* \[ui\] Fixed download button in AccessLog component
* \[curieproxy\] exclude sig new format bug fixed
* \[ui\] waf reason UI fixed
* \[images\] grafana image: fix permissions for provisioned dashboards & datasources
* \[ui\] Fix indentation of WAF policy editor and WAF signature viewer content
* \[ui\] Fix bug preventing docs from being downloaded
* \[ui\] Fix name of all download buttons \(removed unneeded 'x'\)
* \[ui\] Fix bug where first load of document editor page would not load docs correctly
* \[confserver\] Fixed wrong bucket name in bootstrap data \(duplicated prod instead of prod + devops\)
* \[ui\] Fix bug where first load of document editor page would not load docs correctly
```

**Comment by jdorfman** [comment]
@flaper87 want me to add it to GitBook?

**Comment by flaper87** [comment]
> @flaper87 want me to add it to GitBook?

Yeah! I didn't feel like editing the file myself since you are leading this effort.

**Comment by flaper87** [comment]
I have updated the issue description and title to use `1.3.0` instead as discussed.

**Comment by jdorfman** [comment]
✅ https://docs.curiefense.io/v/1.3.0/reference/release-notes
