### ISSUE TITLE
Fix fluentd support in helm

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#98]
**Describe the bug**
Now that elasticsearch uses data streams rather than a fixed index, fluentd must be made to support it.

**To Reproduce**
Run helm deployment with fluentd:
```
./deploy.sh -f curiefense/use-es-fluentd.yaml
```

**Expected behavior**
Logs are properly forwarded by fluentd

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Comment by xavier-rbz** [comment]
Fluentd support of data streams is [very recent](https://github.com/uken/fluent-plugin-elasticsearch/pull/859).

It absolutely wants to [create](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch_data_stream.rb#L37) an index template/ilm policy/index template/data stream, which we already handle in [curielogger init scripts](https://github.com/curiefense/curiefense/blob/master/curiefense/images/curielogger/init/start_curielogger.sh)

**Comment by flaper87** [comment]
@xavier-rbz We chatted about this but I'll add it here just for context. I think it's fine to require datastreams to be off when using fluentd until the fluentd implementation is more mature. If datastreams are off, then we can stick with the current configs, if they are on we can switch to the new one.

**Comment by xavier-rbz** [comment]
Agreed, that's what I ended up doing in https://github.com/curiefense/curiefense/pull/97/commits/e094c90924045b74be9eb39db00c6c08faa8f352
#97 fixes this, closing.
